"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Plus } from "lucide-react"
import { Field, MessageBar, ProcurementShell, WorkPanel, StateBadge, fieldClass, primaryButton, secondaryButton } from "@/components/procurement/procurement-shell"
import { LabelPrintControls } from "@/components/procurement/label-print-controls"
import { LotLabels } from "@/components/procurement/lot-labels"
import { useAuth } from "@/context/AuthContext"
import { purchaseApi } from "@/lib/api"
import { businessDate } from "@/lib/business-date"

export default function ReceiptRegister({ receiptId }: { receiptId?: string }) {
  const client = useQueryClient(); const { activePlant } = useAuth()

  const [search, setSearch] = useState(""); const [filter, setFilter] = useState("ALL"); const selectedId = receiptId || ""
  const [page, setPage] = useState(0)
  const query = useQuery({ queryKey: ["purchase-v2", "receipts", activePlant, page, search, filter], enabled: Boolean(activePlant && activePlant !== "ALL"), queryFn: () => purchaseApi.getGovernedReceipts({ offset: page * 100, limit: 100, q: search || undefined, receipt_kind: ["MANUAL", "PO_LINKED"].includes(filter) ? filter : undefined, invoice_pending: filter === "PENDING" ? true : undefined }) })
  const [reason, setReason] = useState(""); const [error, setError] = useState("")
  const [invoice, setInvoice] = useState({ number: "", date: businessDate(), rates: {} as Record<string, string>, quantities: {} as Record<string, string> })
  useEffect(() => { setInvoice({ number: "", date: businessDate(), rates: {}, quantities: {} }); setReason(""); setError("") }, [receiptId, activePlant])
  const rows: any[] = query.data?.data?.items || []
  const receiptQuery = useQuery({ queryKey: ["purchase-v2", "receipt", activePlant, receiptId], queryFn: () => purchaseApi.getGovernedReceipt(receiptId!), enabled: Boolean(activePlant && activePlant !== "ALL") && Boolean(receiptId) })
  const selected = receiptQuery.data?.data || rows.find((row) => row.id === selectedId)
  const visible = rows.filter((row) => (filter === "ALL" || (filter === "PENDING" ? row.invoice_pending : row.receipt_kind === filter)) && `${row.grn_no} ${row.po_no || ""} ${row.supplier_name || ""} ${row.invoice_no || ""}`.toLowerCase().includes(search.toLowerCase()))
  const refresh = () => client.invalidateQueries({ queryKey: ["purchase-v2"] })
  const failed = (caught: any) => setError(typeof caught?.response?.data?.detail === "string" ? caught.response.data.detail : caught.message)
  const approve = useMutation({ mutationFn: () => purchaseApi.approveManualReceipt(selected.id, { expected_version: selected.posting_version, reason }), onSuccess: () => { refresh(); setReason(""); setError("") }, onError: failed })
  const attach = useMutation({ mutationFn: () => purchaseApi.attachReceiptInvoice(selected.id, { expected_version: selected.posting_version, invoice_no: invoice.number, invoice_date: invoice.date, currency: "INR", lines: selected.lines.map((line: any) => ({ receipt_line_id: line.id, invoice_quantity: Number(invoice.quantities[line.id] ?? line.quantity), invoice_rate: Number(invoice.rates[line.id]) })) }), onSuccess: () => { refresh(); setError("") }, onError: failed })
  return <ProcurementShell eyebrow="Stores / receipt register" title={receiptId ? selected?.grn_no || "Goods receipt" : "GRNs, invoices & lot labels"} description="Find saved manual and PO-linked receipts, attach delayed invoices, review manual purchases and reprint the original QR labels." actions={<Link className={primaryButton} href="/purchase/inward"><Plus className="h-4 w-4" /> New inward</Link>}>
    {error || query.isError || receiptQuery.isError ? <MessageBar tone="error">{error || "Receipts could not load. Refresh and try again."}</MessageBar> : null}
    {receiptId ? <Link className={secondaryButton} href="/purchase/receipts">All GRNs & invoices</Link> : <><div className="flex flex-wrap gap-3"><input aria-label="Search receipts" className={`${fieldClass} max-w-md`} value={search} onChange={(event) => { setSearch(event.target.value); setPage(0) }} placeholder="Search GRN, vendor, PO or invoice" /><select aria-label="Receipt filter" className={`${fieldClass} max-w-xs`} value={filter} onChange={(event) => { setFilter(event.target.value); setPage(0) }}><option value="ALL">All receipts</option><option value="PO_LINKED">Against PO</option><option value="MANUAL">Manual GRNs</option><option value="PENDING">Invoice pending</option></select></div>
    <WorkPanel title="Receipt register" description={`${query.data?.data?.total || 0} matching receipts · select a row to inspect its materials and labels.`} action={<div className="flex gap-2"><a className={secondaryButton} href={purchaseApi.registerExportUrl("receipts", "xlsx")}>Full Excel</a><a className={secondaryButton} href={purchaseApi.registerPdfUrl("receipts")} target="_blank" rel="noreferrer">Print register</a><button className={secondaryButton} disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><button className={secondaryButton} disabled={(page + 1) * 100 >= (query.data?.data?.total || 0)} onClick={() => setPage(page + 1)}>Next</button></div>}><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr>{["GRN / date", "Vendor", "Source", "Invoice", "Lots", "Commercial", ""].map((heading) => <th key={heading} className="px-3 py-3">{heading}</th>)}</tr></thead><tbody>{visible.map((row) => <tr key={row.id} className={`border-b border-border ${selectedId === row.id ? "bg-signal-cyan-soft" : "hover:bg-muted"}`}><td className="max-w-64 break-all px-3 py-3 font-medium">{row.grn_no}<p className="mt-1 text-xs font-normal text-muted-foreground">{row.received_date}</p></td><td className="px-3 py-3">{row.supplier_name || "—"}</td><td className="px-3 py-3">{row.po_no || "Manual GRN"}</td><td className="px-3 py-3">{row.invoice_no || "Pending"}</td><td className="px-3 py-3 tabular-nums">{row.lot_count}</td><td className="px-3 py-3"><StateBadge value={row.commercial_status} /></td><td className="px-3 py-3"><Link className={secondaryButton} href={`/purchase/receipts/${row.id}`}>Open</Link></td></tr>)}</tbody></table>{!visible.length ? <p className="py-8 text-center text-sm text-muted-foreground">{query.isLoading ? "Loading receipts…" : "No receipts match this view."}</p> : null}</div></WorkPanel></>}
    {receiptId && receiptQuery.isLoading ? <p className="p-8 text-sm text-muted-foreground">Loading receipt and labels…</p> : null}
    {selected ? <>
      <WorkPanel title={selected.po_no || "Manual goods receipt"} description={`${selected.grn_no} · ${selected.supplier_name || ""}`}>
        {selected.manual_reason ? <p className="mb-4 text-sm text-muted-foreground">Manual receipt reason: {selected.manual_reason}</p> : null}
        <div className="space-y-3">{selected.lines.map((line: any) => <article key={line.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3"><div><p className="font-medium">{line.item_code} · {line.item_name}</p><p className="mt-1 text-xs text-muted-foreground">{line.quantity} {line.uom} · {line.po_rate == null ? "No PO rate" : `PO ₹${line.po_rate}`} · Invoice {line.invoice_rate == null ? "pending" : `₹${line.invoice_rate}`}</p></div><div className="flex items-center gap-2"><StateBadge value={`QC ${line.qc_status}`} /><Link className={secondaryButton} href="/quality/incoming">Inspect in Quality Control</Link></div></article>)}</div>
        <div className="mt-4"><Field label="Commercial review reason"><input className={fieldClass} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Record commercial approval reason" /></Field></div>
        {selected.commercial_status === "MANUAL_REVIEW" ? <button className={`${primaryButton} mt-3`} disabled={approve.isPending || reason.trim().length < 3} onClick={() => approve.mutate()}>Approve manual purchase and invoice rates</button> : null}
        {["REVIEW_REQUIRED", "MANUAL_REVIEW"].includes(selected.commercial_status) ? <Link className={`${secondaryButton} mt-3`} href="/purchase/discrepancies">Review invoice differences</Link> : null}
        {selected.approval_history?.length ? <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Approval history</summary><ol className="mt-2 space-y-2">{selected.approval_history.map((event: any, index: number) => <li key={index} className="border-l-2 border-signal-cyan-line pl-3 text-xs leading-5"><strong>{event.action.replaceAll("_", " ")}</strong> · {event.actor} · {event.at}<p>{event.reason}</p></li>)}</ol></details> : null}
      </WorkPanel>
      {selected.invoice_pending ? <WorkPanel title="Attach supplier invoice" description="All received materials must have an invoice rate. Differences from the saved PO revision open review cases; manual receipts remain held for approval."><div className="grid gap-3 md:grid-cols-2"><Field label="Invoice number"><input className={fieldClass} value={invoice.number} onChange={(event) => setInvoice({ ...invoice, number: event.target.value })} /></Field><Field label="Invoice date"><input className={fieldClass} type="date" value={invoice.date} onChange={(event) => setInvoice({ ...invoice, date: event.target.value })} /></Field>{selected.lines.map((line: any) => <div key={line.id} className="grid grid-cols-2 gap-3"><Field label={`${line.item_code} invoice quantity · ${line.uom}`}><input className={fieldClass} type="number" min="0.001" step="0.001" value={invoice.quantities[line.id] ?? line.quantity} onChange={(event) => setInvoice({ ...invoice, quantities: { ...invoice.quantities, [line.id]: event.target.value } })} /></Field><Field label={`${line.item_code} invoice rate`}><input className={fieldClass} type="number" min="0" step="0.0001" value={invoice.rates[line.id] ?? ""} onChange={(event) => setInvoice({ ...invoice, rates: { ...invoice.rates, [line.id]: event.target.value } })} /></Field></div>)}</div><button className={`${primaryButton} mt-4`} disabled={attach.isPending || !invoice.number.trim() || selected.lines.some((line: any) => invoice.rates[line.id] == null || invoice.rates[line.id] === "")} onClick={() => attach.mutate()}>Attach and validate invoice</button></WorkPanel> : null}
      {selected.lots.length ? <><LabelPrintControls lots={selected.lots} /><LotLabels lots={selected.lots} /></> : null}
    </> : null}
  </ProcurementShell>
}
