"use client"

import { parseScheduleSheet, mergeScheduleCells } from "@/lib/schedule-workbook"
import { businessDate } from "@/lib/business-date"

import { useEffect, useMemo, useRef, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { CalendarDays, FileSpreadsheet, Play, Save, ShoppingCart, Target } from "lucide-react"

import { useAuth } from "@/context/AuthContext"
import { EmptyState } from "@/components/erp/shell"
import { RequestErrors, Field, MessageBar, ProcurementShell, StateBadge, SummaryCard, WorkPanel, fieldClass, primaryButton, secondaryButton } from "@/components/procurement/procurement-shell"
import { useInventoryItems } from "@/hooks/use-inventory"
import { useVendors } from "@/hooks/use-master-data"
import { purchaseApi } from "@/lib/api"
import type { ProcurementPlan, ProcurementPlanEntry } from "@/lib/procurement-types"

const currentMonth = () => businessDate().slice(0, 7)
const dateKey = (date: Date) => date.toISOString().slice(0, 10)
const cellKey = (day: string, itemId: string) => `${day}:${itemId}`
const aliasKey = (value: string) => value.trim().toUpperCase().replace(/\s+/g, " ")
function daysIn(month: string) { const [year, value] = month.split("-").map(Number); const end = new Date(Date.UTC(year, value, 0)).getUTCDate(); return Array.from({ length: end }, (_, index) => new Date(Date.UTC(year, value - 1, index + 1))) }

export default function PurchaseSchedulerPage() {
  const { activePlant } = useAuth(); const client = useQueryClient(); const itemsQuery = useInventoryItems(); const vendorsQuery = useVendors()
  const items: any[] = useMemo(() => (Array.isArray(itemsQuery.data) ? itemsQuery.data.filter((row: any) => String(row.type) === "RAW_PAPER") : []), [itemsQuery.data])
  const vendors: any[] = Array.isArray(vendorsQuery.data) ? vendorsQuery.data : []
  const [view, setView] = useState<"calendar" | "grid">("calendar"); const [selectedDay, setSelectedDay] = useState(""); const [mrpResult, setMrpResult] = useState<any>(null)
  const editSnapshot = useRef<{ id: string; version: number; dirty: boolean } | null>(null)
  const [month, setMonth] = useState(currentMonth()); const [selectedPlanId, setSelectedPlanId] = useState("")
  const [laneIds, setLaneIds] = useState<string[]>([]); const [cells, setCells] = useState<Record<string, string>>({})
  const [targetLane, setTargetLane] = useState(""); const [laneVendors, setLaneVendors] = useState<Record<string, string>>({}); const [target, setTarget] = useState("")
  const [workbookSheets, setWorkbookSheets] = useState<any[]>([]); const [importSheetName, setImportSheetName] = useState("")
  const [importRows, setImportRows] = useState<Array<{ date: string; header: string; qty: number; cell: string; item_id?: string }>>([])
  const [importAliases, setImportAliases] = useState<Record<string, string>>({})
  const [importUnit, setImportUnit] = useState<"" | "KG" | "MT">("")
  const [importSource, setImportSource] = useState<{ hash: string; sheet: string; file: string } | null>(null)
  const [importEvidence, setImportEvidence] = useState<Record<string, string>>({})
  const [notice, setNotice] = useState<{ tone: "success" | "error" | "info"; text: string } | null>(null)
  const plansQuery = useQuery({ queryKey: ["purchase-v2", "plans", activePlant, month], enabled: Boolean(activePlant && activePlant !== "ALL"), refetchOnWindowFocus: false, queryFn: () => purchaseApi.getPlans({ month: `${month}-01` }) })
  const plans: ProcurementPlan[] = useMemo(() => plansQuery.data?.data?.items || [], [plansQuery.data]); const selected = useMemo(() => plans.find((plan) => plan.id === selectedPlanId) || plans[0], [plans, selectedPlanId])
  const demand = useQuery({ queryKey: ["purchase-v2", "sales-bom-demand", activePlant, month], enabled: Boolean(activePlant && activePlant !== "ALL"), queryFn: () => purchaseApi.getMaterialDemand({ as_of_date: `${month}-01`, horizon_end: dateKey(daysIn(month).at(-1)!) }) })
  const requirements: any[] = useMemo(() => demand.data?.data?.requirements || [], [demand.data])
  const blocked: any[] = demand.data?.data?.blocked || []
  const { demandTotals, demandByDay, demandByItem } = useMemo(() => {
    const totals: Record<string, number> = {}; const byDay: Record<string, number> = {}; const byItem: Record<string, any[]> = {}
    for (const row of requirements) {
      totals[row.item_id] = (totals[row.item_id] || 0) + row.qty_kg
      byDay[row.date] = (byDay[row.date] || 0) + row.qty_kg
      ;(byItem[row.item_id] ||= []).push(row)
    }
    return { demandTotals: totals, demandByDay: byDay, demandByItem: byItem }
  }, [requirements])
  const editable = selected?.status === "DRAFT"
  const dates = useMemo(() => daysIn(month), [month]); const lanes = laneIds.map((id) => items.find((row) => String(row.id) === id)).filter(Boolean)

  useEffect(() => { if (plans[0] && !selectedPlanId) setSelectedPlanId(plans[0].id) }, [plans, selectedPlanId])
  useEffect(() => {
    if (!selected) { editSnapshot.current = null; setCells({}); setLaneVendors({}); setLaneIds([]); return }
    if (editSnapshot.current?.id === selected.id && editSnapshot.current.dirty) return
    editSnapshot.current = { id: selected.id, version: selected.version, dirty: false }
    const nextCells: Record<string, string> = {}; const nextVendors: Record<string, string> = {}; const nextLanes: string[] = []
    selected.entries.forEach((entry) => { nextCells[cellKey(entry.entry_date, entry.item_id)] = String(entry.qty_kg); if (entry.supplier_id) nextVendors[entry.item_id] = entry.supplier_id; if (!nextLanes.includes(entry.item_id)) nextLanes.push(entry.item_id) })
    setCells(nextCells); setLaneVendors(nextVendors); setLaneIds(nextLanes)
  }, [selected])

  function markCalendarDirty() { if (editSnapshot.current) editSnapshot.current.dirty = true }
  useEffect(() => { setSelectedPlanId(""); setMrpResult(null); setSelectedDay(""); setImportRows([]); setWorkbookSheets([]); setImportSource(null); setImportEvidence({}); setImportUnit(""); setNotice(null) }, [activePlant, month])
  const total = Object.values(cells).reduce((sum, value) => sum + Number(value || 0), 0); const activeDays = new Set(Object.entries(cells).filter(([, value]) => Number(value) > 0).map(([key]) => key.slice(0, 10))).size
  const refresh = () => client.invalidateQueries({ queryKey: ["purchase-v2"] })
  const createPlan = useMutation({ mutationFn: () => purchaseApi.createPlan({ request_id: crypto.randomUUID(), month: `${month}-01`, name: `RM Schedule ${month}`, target_mode: "ARRIVAL", working_calendar: { sunday: "OFF", source: "LIVE_CALENDAR" }, entries: [] }), onSuccess: ({ data }) => { setSelectedPlanId(data.id); setNotice({ tone: "success", text: "Monthly procurement plan created. Add material lanes and daily kg." }); refresh() } })
  function entries(): ProcurementPlanEntry[] { return dates.flatMap((day) => lanes.map((item: any) => { const key = cellKey(dateKey(day), item.id); const old = selected?.entries.find((entry) => entry.entry_date === dateKey(day) && entry.item_id === item.id); return { id: old?.id, entry_date: dateKey(day), item_id: item.id, supplier_id: laneVendors[item.id] || old?.supplier_id || undefined, supplier_name: vendors.find((vendor: any) => String(vendor.id) === (laneVendors[item.id] || old?.supplier_id))?.name || old?.supplier_name || undefined, material_form: old?.material_form || "REEL", qty_kg: Number(cells[key] || 0), expected_unit_count: old?.expected_unit_count, notes: importEvidence[key] || old?.notes } as ProcurementPlanEntry }).filter((entry) => entry.qty_kg > 0 || Boolean(entry.id))) }
  const save = useMutation({ mutationFn: () => purchaseApi.updatePlanEntries(selected!.id, { expected_version: editSnapshot.current?.version ?? selected!.version, entries: entries(), source_hash: importSource?.hash, source_metadata: importSource ? { file_name: importSource.file, sheet: importSource.sheet, original_unit: importUnit, factor_to_kg: importUnit === "MT" ? 1000 : 1 } : undefined }), onSuccess: () => { if (editSnapshot.current) editSnapshot.current.dirty = false; setNotice({ tone: "success", text: "All daily kg entries and import evidence saved with a new plan version." }); refresh() }, onError: (error: any) => setNotice({ tone: "error", text: error?.response?.data?.detail || error.message }) })
  const planAction = useMutation({ mutationFn: async (action: string) => {
    let version = editSnapshot.current?.version ?? selected!.version
    if (action === "SUBMIT") {
      const saved = await purchaseApi.updatePlanEntries(selected!.id, { expected_version: version, entries: entries() })
      version = saved.data.version
      if (editSnapshot.current) { editSnapshot.current.version = version; editSnapshot.current.dirty = false }
    }
    return purchaseApi.actOnPlan(selected!.id, { action, expected_version: version, reason: action === "REJECT" ? "Planning revision required" : undefined })
  }, onSuccess: ({ data }) => { setNotice({ tone: "success", text: `Plan moved to ${data.status}.` }); refresh() }, onError: (error: any) => setNotice({ tone: "error", text: error?.response?.data?.detail || error.message }) })
  const convert = useMutation({ mutationFn: () => purchaseApi.convertPlan(selected!.id, { request_id: crypto.randomUUID(), expected_plan_version: selected!.version, entry_ids: selected!.entries.filter((entry) => entry.qty_kg > Number(entry.converted_qty_kg || 0)).map((entry) => entry.id) }), onSuccess: ({ data }) => { setNotice({ tone: "success", text: `${data.purchase_order_ids.length} vendor-grouped PO draft(s) created once.` }); refresh() }, onError: (error: any) => setNotice({ tone: "error", text: error?.response?.data?.detail || error.message }) })
  const mrp = useMutation({ mutationFn: () => purchaseApi.runMrp({ as_of_date: `${month}-01`, horizon_end: dateKey(dates[dates.length - 1]), demand_source_version: demand.data!.data.source_version, items: Object.entries(demandTotals).map(([item_id, demand_kg]) => ({ item_id, demand_kg, dated_demand: (demandByItem[item_id] || []).map((row) => ({ date: row.date, qty_kg: row.qty_kg })) })) }), onSuccess: ({ data }) => { setMrpResult(data); setNotice({ tone: "info", text: "MRP saved from open sales-order BOM requirements. Review each material and stage shortages into the calendar." }) }, onError: (error: any) => setNotice({ tone: "error", text: error?.response?.data?.detail || error.message }) })
  function stageSuggestion(row: any) {
    const alreadyPlanned = Object.entries(cells).filter(([key]) => key.endsWith(`:${row.item_id}`)).reduce((sum, [, value]) => sum + Number(value || 0), 0)
    const additional = Math.max(0, row.suggested_order_kg - alreadyPlanned)
    if (additional <= 0) { setNotice({ tone: "info", text: `${row.item_code}: this calendar already covers the suggested ${row.suggested_order_kg.toLocaleString("en-IN")} kg. Review delivery timing before adding more.` }); return }
    const day = row.first_shortage_date || requirements.filter((requirement) => requirement.item_id === row.item_id).map((requirement) => requirement.date).sort()[0] || `${month}-01`
    markCalendarDirty()
    setLaneIds((current) => Array.from(new Set([...current, row.item_id])))
    setCells((current) => ({ ...current, [cellKey(day, row.item_id)]: String(Number(current[cellKey(day, row.item_id)] || 0) + additional) }))
    setSelectedDay(day); setNotice({ tone: "info", text: `${row.item_code}: ${additional.toLocaleString("en-IN")} additional kg staged for ${day}. Assign the vendor, review timing and save.` })
  }
  async function exportCalendar() {
    const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); const sheet = workbook.addWorksheet(month)
    sheet.addRow(["Date", "Day", ...lanes.map((item: any) => item.item_code), "Total kg"])
    dates.forEach((day) => { const quantities = lanes.map((item: any) => Number(cells[cellKey(dateKey(day), item.id)] || 0)); sheet.addRow([dateKey(day), day.toLocaleDateString("en-IN", { weekday: "long", timeZone: "UTC" }), ...quantities, quantities.reduce((a, b) => a + b, 0)]) })
    sheet.views = [{ state: "frozen", xSplit: 2, ySplit: 1 }]; sheet.columns.forEach((column) => { column.width = 18 })
    sheet.getRow(1).font = { bold: true }; sheet.pageSetup = { orientation: "landscape", paperSize: 9, fitToPage: true, fitToWidth: 1, fitToHeight: 0 }
    const blob = new Blob([await workbook.xlsx.writeBuffer()], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `RM-Schedule-${month}.xlsx`; link.click(); URL.revokeObjectURL(url)
  }

  function fillTarget() {
    const targetMaterial = lanes.find((lane: any) => lane.id === targetLane) || lanes[0]
    if (!targetMaterial || Number(target) <= 0) return
    const working = dates.filter((day) => day.getUTCDay() !== 0); const base = Math.floor(Number(target) * 1000 / working.length) / 1000
    let remaining = Math.round(Number(target) * 1000) / 1000; const next = { ...cells }
    dates.forEach((day) => { delete next[cellKey(dateKey(day), targetMaterial.id)] })
    working.forEach((day, index) => { const qty = index === working.length - 1 ? remaining : base; next[cellKey(dateKey(day), targetMaterial.id)] = qty.toFixed(3); remaining = Math.round((remaining - qty) * 1000) / 1000 })
    markCalendarDirty()
    setCells(next); setNotice({ tone: "info", text: `${Number(target).toLocaleString("en-IN")} kg allocated across ${working.length} working days. Review vendor capacity before saving.` })
  }

  async function importWorkbook(file: File) {
    try {
      const ExcelJS = await import("exceljs"); const workbook = new ExcelJS.Workbook(); const buffer = await file.arrayBuffer(); await workbook.xlsx.load(buffer)
      const digest = Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", buffer))).map((byte) => byte.toString(16).padStart(2, "0")).join("")
      const sheets = workbook.worksheets.map((sheet) => ({ name: sheet.name, ...parseScheduleSheet(sheet) }))
      if (!sheets.length) throw new Error("Workbook has no worksheet")
      setWorkbookSheets(sheets)
      const matchedSheet = sheets.find((sheet) => sheet.rows.some((row) => row.date.startsWith(month))) || sheets[0]
      selectImportSheet(matchedSheet, { hash: digest, sheet: matchedSheet.name, file: file.name })
    } catch (error: any) { setNotice({ tone: "error", text: error.message || "Workbook could not be read" }) }
  }
  function selectImportSheet(sheet: any, source = importSource) {
    const preview = sheet.rows.map((row: any) => ({ ...row, item_id: items.find((item) => aliasKey(row.header) === aliasKey(String(item.item_code)))?.id }))
    setImportSheetName(sheet.name); setImportRows(preview); setImportAliases({})
    if (source) setImportSource({ ...source, sheet: sheet.name })
    setNotice({ tone: "info", text: `${sheet.name}: ${preview.length} cells from the first daily scheduling block. ${sheet.ignoredDatedRows} dated rows outside that block excluded (for example finished-goods targets). Choose units and map materials; explicitly exclude helper columns.` })
  }
  const importedItemId = (row: { header: string; item_id?: string }) => row.item_id || importAliases[row.header]
  function applyImport() {
    if (!importUnit || importRows.some((row) => !importedItemId(row) || !row.date.startsWith(month))) return
    const matched = importRows.filter((row) => importedItemId(row) !== "IGNORE").map((row) => ({ ...row, item_id: importedItemId(row)! }))
    const merged = mergeScheduleCells(matched, importUnit === "MT" ? 1000 : 1)
    markCalendarDirty()
    setLaneIds((current) => Array.from(new Set([...current, ...matched.map((row) => row.item_id)])))
    setCells((current) => ({ ...current, ...merged.cells }))
    setImportEvidence((current) => ({ ...current, ...Object.fromEntries(Object.entries(merged.sources).map(([key, sources]) => [key, JSON.stringify({ source_file: importSource?.file, source_hash: importSource?.hash, sheet: importSource?.sheet, sources, original_unit: importUnit, factor_to_kg: importUnit === "MT" ? 1000 : 1 })])) }))
    setNotice({ tone: "success", text: `${matched.length} source cells combined into ${Object.keys(merged.cells).length} material/date totals in kg. Matching existing calendar cells were replaced; other dates are unchanged. Review and save.` })
  }

  return <ProcurementShell eyebrow="Monthly RM scheduler" title="Plan daily paper arrivals on a live kg calendar."
    description="The grid follows the client's date-row workbook while using saved material IDs, vendor lanes and real month lengths. MRP records stock, demand, approved supply, policy and cost versions before PO conversion.">
    <RequestErrors errors={[createPlan.error, plansQuery.error]} />
    {notice ? <MessageBar tone={notice.tone}>{notice.text}</MessageBar> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard label="Planned month" value={month} detail={`${dates.length} actual calendar days`} icon={CalendarDays} tone="slate" /><SummaryCard label="Scheduled" value={`${total.toLocaleString("en-IN")} kg`} detail={`${activeDays} delivery dates`} icon={Target} tone="cyan" /><SummaryCard label="Material lanes" value={lanes.length} detail="Saved master mappings" icon={FileSpreadsheet} tone="amber" /><SummaryCard label="Plan status" value={<StateBadge value={selected?.status || "NOT_CREATED"} />} detail={selected ? `Version ${selected.version}` : "Create plan to begin"} icon={ShoppingCart} tone="emerald" /></section>
    <WorkPanel title="Plan controls" description="Create one saved month, choose material/vendor lanes, or preview the reference workbook before staging mapped cells.">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6"><Field label="Month"><input className={fieldClass} type="month" value={month} onChange={(e) => { if (!e.target.value) return; setMonth(e.target.value); setSelectedPlanId(""); setMrpResult(null); setSelectedDay("") }} /></Field><Field label="Plan"><select className={fieldClass} value={selected?.id || ""} onChange={(e) => setSelectedPlanId(e.target.value)}><option value="">No plan</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.status}</option>)}</select></Field><Field label="Add material lane"><select className={fieldClass} value="" disabled={!editable} onChange={(e) => e.target.value && setLaneIds((current) => current.includes(e.target.value) ? current : [...current, e.target.value])}><option value="">Select paper</option>{items.filter((item) => !laneIds.includes(String(item.id))).map((item) => <option key={item.id} value={item.id}>{item.item_code} · {item.name}</option>)}</select></Field><Field label="Import Excel"><input className={`${fieldClass} py-2`} type="file" accept=".xlsx,.xlsm" onChange={(e) => e.target.files?.[0] && importWorkbook(e.target.files[0])} /></Field><Field label="Workbook quantity unit" hint="required"><select className={fieldClass} value={importUnit} onChange={(e) => setImportUnit(e.target.value as "" | "KG" | "MT")}><option value="">Select source unit</option><option value="KG">kg · factor 1</option><option value="MT">MT · factor 1,000</option></select></Field><div className="flex items-end"><button className={primaryButton} disabled={!activePlant || activePlant === "ALL" || plansQuery.isPending || plansQuery.isFetching || plansQuery.isError || Boolean(selected) || createPlan.isPending} onClick={() => createPlan.mutate()}>Create month plan</button></div></div>
      {workbookSheets.length ? <div className="mt-3 max-w-sm"><Field label="Worksheet"><select className={fieldClass} value={importSheetName} onChange={(event) => selectImportSheet(workbookSheets.find((sheet) => sheet.name === event.target.value))}>{workbookSheets.map((sheet) => <option key={sheet.name}>{sheet.name}</option>)}</select></Field></div> : null}
      {importRows.length ? <div className="mt-4 rounded-lg border border-signal-amber-line bg-signal-amber-soft p-4"><p className="text-sm font-semibold text-signal-amber-ink">Workbook preview: {importRows.length} positive dated cells · {importRows.filter((row) => importedItemId(row)).length} mapped · {importRows.filter((row) => !importedItemId(row)).length} blocked · {importRows.filter((row) => !row.date.startsWith(month)).length} outside selected month</p>{Array.from(new Set(importRows.filter((row) => !row.item_id).map((row) => row.header))).length ? <div className="mt-3 grid gap-2 md:grid-cols-2">{Array.from(new Set(importRows.filter((row) => !row.item_id).map((row) => row.header))).map((header) => <label key={header} className="rounded-lg border border-signal-amber-line bg-card p-3 text-xs font-semibold text-muted-foreground"><span className="block truncate" title={header}>{header}</span><select aria-label={`Map ${header}`} className={`${fieldClass} mt-2`} value={importAliases[header] || ""} onChange={(e) => setImportAliases((current) => ({ ...current, [header]: e.target.value }))}><option value="">Choose exact material</option><option value="IGNORE">Exclude helper / non-paper column</option>{items.map((item) => <option key={item.id} value={item.id}>{item.item_code} · {item.name}</option>)}</select></label>)}</div> : null}<button className={`${secondaryButton} mt-3`} onClick={applyImport} disabled={!editable || !importUnit || importRows.some((row) => !importedItemId(row) || !row.date.startsWith(month))}>Stage mapped cells as kg</button></div> : null}
    </WorkPanel>
    <WorkPanel title={new Date(`${month}-01T12:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" })} description="Select a date to enter planned arrivals. Amber is required material; teal is a scheduled arrival. All paper quantities are kg." action={<div className="flex flex-wrap gap-2"><button className={secondaryButton} onClick={() => setView(view === "calendar" ? "grid" : "calendar")}>{view === "calendar" ? "Workbook grid" : "Month calendar"}</button><button className={secondaryButton} disabled={!lanes.length} onClick={exportCalendar}>Excel</button><button className={secondaryButton} onClick={() => window.print()}>Print</button></div>}>
      {view === "calendar" ? <><div className="overflow-x-auto"><div className="min-w-[700px]"><div className="grid grid-cols-7 border-b border-border">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div key={day} className="px-3 py-2 text-xs font-semibold text-muted-foreground">{day}</div>)}</div><div className="grid grid-cols-7 border-l border-border">{Array.from({ length: (dates[0].getUTCDay() + 6) % 7 }, (_, index) => <div key={`blank-${index}`} className="border-b border-r border-border bg-muted" />)}{dates.map((date) => { const day = dateKey(date); const arrivals = lanes.filter((item: any) => Number(cells[cellKey(day, item.id)]) > 0); const needed = (demandByDay[day] || 0); return <button type="button" key={day} aria-label={`Plan arrivals ${day}`} onClick={() => setSelectedDay(day)} className={`min-h-28 border-b border-r border-border p-2 text-left align-top focus-visible:z-10 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-700 ${selectedDay === day ? "bg-signal-cyan-soft" : date.getUTCDay() === 0 ? "bg-muted" : "bg-card hover:bg-signal-cyan-soft/40"}`}><span className={`inline-flex h-7 w-7 items-center justify-center rounded-full text-sm font-semibold ${day === businessDate() ? "bg-primary text-primary-foreground" : "text-muted-foreground"}`}>{date.getUTCDate()}</span>{needed > 0 ? <p className="mt-2 rounded bg-signal-amber-soft px-1.5 py-1 text-[11px] font-medium text-signal-amber-ink">Need {needed.toLocaleString("en-IN")} kg</p> : null}{arrivals.slice(0, 3).map((item: any) => <p key={item.id} className="mt-1 truncate rounded bg-signal-cyan-soft/70 px-1.5 py-1 text-[11px] font-medium text-signal-cyan-ink">{item.item_code} · {Number(cells[cellKey(day, item.id)]).toLocaleString("en-IN")}</p>)}{arrivals.length > 3 ? <p className="mt-1 text-xs text-muted-foreground">+{arrivals.length - 3} materials</p> : null}</button> })}</div></div></div>
      {selectedDay ? <div className="mt-5 rounded-xl border border-signal-cyan-line bg-signal-cyan-soft/40 p-4"><h3 className="font-semibold">Arrivals · {selectedDay}</h3>{!selected || !lanes.length ? <p className="mt-2 text-sm text-muted-foreground">Create a month plan and add a material lane above to enter arrivals.</p> : <div className="mt-3 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{lanes.map((item: any) => <div key={item.id} className="rounded-lg border border-border bg-card p-3"><Field label={`${item.item_code} kg`}><input className={fieldClass} type="number" min="0" step="0.001" disabled={!editable} value={cells[cellKey(selectedDay, item.id)] || ""} onChange={(event) => { markCalendarDirty(); setCells({ ...cells, [cellKey(selectedDay, item.id)]: event.target.value }) }} /></Field><select aria-label={`${item.item_code} arrival vendor`} className={`${fieldClass} mt-2`} disabled={!editable} value={laneVendors[item.id] || ""} onChange={(event) => { markCalendarDirty(); setLaneVendors({ ...laneVendors, [item.id]: event.target.value }) }}><option value="">Assign vendor</option>{vendors.map((vendor) => <option key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</select></div>)}</div>}</div> : null}</> : <p className="text-sm text-muted-foreground">Workbook view is below. Switch to Month calendar to see the delivery dates.</p>}
    </WorkPanel>
    {view === "grid" ? <WorkPanel title="Monthly grid" description="Date and day stay frozen. Each numeric cell is kg; zero is a real blank plan value. Horizontal scroll is contained inside the grid.">
      {!selected ? <EmptyState label="Create or select the monthly plan before editing the calendar." /> : !lanes.length ? <EmptyState label="Add at least one raw-paper lane." /> : <div className="overflow-auto rounded-lg border border-border max-h-[620px]"><table className="w-full min-w-max border-separate border-spacing-0 text-sm"><thead className="sticky top-0 z-20 bg-[hsl(var(--surface-2))] text-muted-foreground"><tr><th className="sticky left-0 z-30 min-w-28 border-b border-r border-border bg-[hsl(var(--surface-2))] px-3 py-3 text-left">Date</th>{lanes.map((item: any) => <th key={item.id} className="min-w-44 border-b border-foreground/80 px-2 py-2 text-left"><p className="font-semibold">{item.item_code}</p><select disabled={!editable} aria-label={`${item.item_code} vendor`} className="mt-2 h-8 w-full rounded-md border border-border/20 bg-card/10 px-2 text-xs text-white" value={laneVendors[item.id] || ""} onChange={(e) => { markCalendarDirty(); setLaneVendors({ ...laneVendors, [item.id]: e.target.value }) }}><option className="text-foreground" value="">Assign vendor</option>{vendors.map((vendor: any) => <option className="text-foreground" key={vendor.id} value={vendor.id}>{vendor.name}</option>)}</select></th>)}</tr></thead><tbody>{dates.map((day) => { const sunday = day.getUTCDay() === 0; return <tr key={dateKey(day)} className={sunday ? "bg-signal-amber-soft" : "bg-card"}><th className={`sticky left-0 z-10 border-b border-r border-border px-3 py-2 text-left ${sunday ? "bg-signal-amber-soft" : "bg-card"}`}><span className="font-semibold tabular-nums">{String(day.getUTCDate()).padStart(2, "0")}</span><span className="ml-2 text-xs text-muted-foreground">{day.toLocaleDateString("en-IN", { weekday: "short", timeZone: "UTC" })}</span></th>{lanes.map((item: any) => <td key={item.id} className="border-b border-r border-border p-1.5"><input disabled={!editable} aria-label={`${item.item_code} ${dateKey(day)} kg`} className="h-9 w-full rounded-md border border-transparent bg-transparent px-2 text-right font-medium tabular-nums outline-none hover:border-border focus:border-signal-cyan-ink/40 focus:bg-signal-cyan-soft" type="number" min="0" step="0.001" value={cells[cellKey(dateKey(day), item.id)] || ""} onChange={(e) => { markCalendarDirty(); setCells({ ...cells, [cellKey(dateKey(day), item.id)]: e.target.value }) }} /></td>)}</tr>})}</tbody><tfoot className="sticky bottom-0 bg-signal-cyan-soft"><tr><th className="sticky left-0 border-r border-signal-cyan-line bg-signal-cyan-soft px-3 py-3 text-left">Monthly kg</th>{lanes.map((item: any) => <td key={item.id} className="px-3 py-3 text-right font-semibold tabular-nums">{dates.reduce((sum, day) => sum + Number(cells[cellKey(dateKey(day), item.id)] || 0), 0).toLocaleString("en-IN")}</td>)}</tr></tfoot></table></div>}
      {selected ? <div className="mt-5 flex flex-wrap gap-2"><button className={primaryButton} disabled={save.isPending || !lanes.length || selected.status !== "DRAFT"} onClick={() => save.mutate()}><Save className="h-4 w-4" /> Save calendar</button>{selected.status === "DRAFT" ? <button className={secondaryButton} onClick={() => planAction.mutate("SUBMIT")}>Submit plan</button> : null}{selected.status === "SUBMITTED" ? <button className={secondaryButton} onClick={() => planAction.mutate("APPROVE")}>Approve plan</button> : null}<button className={secondaryButton} disabled={!requirements.length || demand.isFetching || demand.isError || blocked.length > 0 || mrp.isPending} onClick={() => mrp.mutate()}><Play className="h-4 w-4" /> Run MRP</button>{['APPROVED','LOCKED'].includes(selected.status) ? <button className={secondaryButton} disabled={convert.isPending || !selected.entries.length} onClick={() => convert.mutate()}><ShoppingCart className="h-4 w-4" /> Generate uncovered PO drafts</button> : null}</div> : null}
    </WorkPanel> : null}
    {lanes.length ? <WorkPanel title="Enter number to reach" description="Distribute the selected material target over working days, then adjust each delivery date."><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Field label="Target material"><select className={fieldClass} value={targetLane || lanes[0]?.id || ""} onChange={(event) => setTargetLane(event.target.value)}>{lanes.map((lane: any) => <option key={lane.id} value={lane.id}>{lane.item_code}</option>)}</select></Field><Field label="Monthly target kg"><input className={fieldClass} type="number" min="0" step="1" value={target} onChange={(e) => setTarget(e.target.value)} /></Field><button className={`${secondaryButton} self-end`} disabled={!editable} onClick={fillTarget}>Fill working days</button></div></WorkPanel> : null}
    <WorkPanel title="Materials required by open sales orders" description={demand.data?.data?.basis || "Loading approved sales-order quantities and their canonical recipe BOMs."} action={<button className={secondaryButton} onClick={() => demand.refetch()} disabled={demand.isFetching}>{demand.isFetching ? "Refreshing…" : "Refresh demand"}</button>}>
      {demand.isError ? <MessageBar tone="error">Sales/BOM demand could not load. No zero-demand assumption has been made. Retry when source services are available.</MessageBar> : null}
      {blocked.length ? <MessageBar tone="error">{blocked.length} order line(s) need BOM or material mapping correction. {blocked.map((row) => `${row.order_no}: ${row.reason}`).join("; ")}</MessageBar> : null}
      {requirements.length ? <><div className="max-h-72 overflow-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="sticky top-0 bg-muted text-xs text-muted-foreground"><tr>{["Need by", "Sales order", "Material", "New-build / job units", "Gross kg", "Net issued kg", "Required kg", "Recipe"].map((heading) => <th className="px-3 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody>{requirements.map((row, index) => <tr className="border-t border-border" key={`${row.line_id}:${row.item_id}:${index}`}><td className="px-3 py-3">{row.due_date}{row.overdue ? <span className="ml-2 text-signal-rose-ink">Overdue</span> : null}</td><td className="px-3 py-3">{row.order_no}</td><td className="px-3 py-3 font-medium">{row.item_code}</td><td className="px-3 py-3 tabular-nums">{row.open_units.toLocaleString("en-IN")}</td><td className="px-3 py-3 tabular-nums">{(row.gross_qty_kg ?? row.qty_kg).toLocaleString("en-IN")}</td><td className="px-3 py-3 tabular-nums">{(row.already_issued_kg || 0).toLocaleString("en-IN")}</td><td className="px-3 py-3 tabular-nums">{row.qty_kg.toLocaleString("en-IN")}</td><td className="px-3 py-3">v{row.recipe_version}</td></tr>)}</tbody></table></div><button className={`${primaryButton} mt-4`} disabled={mrp.isPending || blocked.length > 0 || demand.isFetching} onClick={() => mrp.mutate()}><Play className="h-4 w-4" /> Calculate purchase shortages</button></> : !demand.isFetching && !demand.isError ? <p className="text-sm text-muted-foreground">No residual approved sales-order paper demand in this horizon.</p> : null}
      {mrpResult ? <div className="mt-4 space-y-2">{mrpResult.results.map((row: any) => <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-signal-cyan-line bg-signal-cyan-soft/50 p-3" key={row.item_id}><div><p className="font-semibold">{row.item_code} · suggested {row.suggested_order_kg.toLocaleString("en-IN")} kg</p><p className="mt-1 text-xs text-muted-foreground">Demand {row.demand_kg} + target {row.target_stock_kg} − free {row.opening_stock_kg} − confirmed supply {row.committed_supply_kg}</p>{row.peak_timing_shortfall_kg > row.suggested_order_kg ? <p className="mt-2 text-xs font-medium text-signal-amber-ink">Timing gap: {row.peak_timing_shortfall_kg.toLocaleString("en-IN")} kg from {row.first_shortage_date}. Expedite existing PO arrivals or revise dates before adding duplicate supply.</p> : null}{row.unconfirmed_supply_kg > 0 ? <p className="mt-1 text-xs text-signal-amber-ink">{row.unconfirmed_supply_kg} kg has tentative dates and is excluded from coverage.</p> : null}{row.overdue_supply_kg > 0 ? <p className="mt-1 text-xs text-signal-amber-ink">{row.overdue_supply_kg} kg is overdue; re-confirm the arrival date before counting it as supply.</p> : null}{row.undated_open_supply_kg > 0 ? <p className="mt-1 text-xs text-signal-amber-ink">{row.undated_open_supply_kg} kg of open POs has no date and is excluded from coverage.</p> : null}</div><button className={secondaryButton} disabled={!editable || row.suggested_order_kg <= 0} onClick={() => stageSuggestion(row)}>Stage arrival</button></div>)}</div> : null}
    </WorkPanel>
    {selected && view === "calendar" ? <div className="sticky bottom-3 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-4 shadow-lg"><p className="text-sm font-semibold">{total.toLocaleString("en-IN")} kg · {activeDays} delivery dates · {selected.status}</p><div className="flex flex-wrap gap-2"><button className={primaryButton} disabled={!editable || save.isPending || !lanes.length} onClick={() => save.mutate()}>Save calendar</button>{editable ? <button className={secondaryButton} disabled={planAction.isPending} onClick={() => planAction.mutate("SUBMIT")}>Save & submit plan</button> : null}{selected.status === "SUBMITTED" ? <button className={secondaryButton} disabled={planAction.isPending} onClick={() => planAction.mutate("APPROVE")}>Approve plan</button> : null}{selected.status === "APPROVED" ? <button className={primaryButton} disabled={convert.isPending} onClick={() => convert.mutate()}>Generate vendor PO drafts</button> : null}</div></div> : null}
  </ProcurementShell>
}
