"use client"

import { useAuth } from "@/context/AuthContext"
import { useMemo, useState } from "react"
import Link from "next/link"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { BellRing, CheckCircle2, Gauge, Save, ShieldAlert } from "lucide-react"

import { EmptyState } from "@/components/erp/shell"
import { RequestErrors, Field, MessageBar, ProcurementShell, StateBadge, SummaryCard, WorkPanel, fieldClass, primaryButton, secondaryButton } from "@/components/procurement/procurement-shell"
import { RoleGate } from "@/components/workspace/role-gate"
import { useInventoryItems } from "@/hooks/use-inventory"
import { purchaseApi } from "@/lib/api"
import type { StockPolicy } from "@/lib/procurement-types"

export default function StockAlertPoliciesPage() {
  const { activePlant } = useAuth()
  const client = useQueryClient(); const itemsQuery = useInventoryItems(); const items: any[] = useMemo(() => Array.isArray(itemsQuery.data) ? itemsQuery.data.filter((row: any) => String(row.type) !== "FINISHED_GOOD") : [], [itemsQuery.data])
  const query = useQuery({ queryKey: ["purchase-v2", "policies", activePlant], enabled: Boolean(activePlant && activePlant !== "ALL"), queryFn: () => purchaseApi.getStockPolicies() }); const policies: StockPolicy[] = query.data?.data?.items || []
  const [form, setForm] = useState({ item_id: "", safety: "0", reorder: "0", target: "0", recovery: "0", lead: "0", moq: "0", multiple: "0", recipients: "Owner,Planner", cooldown: "24", reason: "" }); const [notice, setNotice] = useState("")
  const refresh = () => client.invalidateQueries({ queryKey: ["purchase-v2"] })
  const create = useMutation({ mutationFn: () => purchaseApi.createStockPolicy({ request_id: crypto.randomUUID(), item_id: form.item_id, stock_basis: "FREE_STOCK", safety_stock_kg: Number(form.safety), reorder_point_kg: Number(form.reorder), target_stock_kg: Number(form.target), recovery_margin_kg: Number(form.recovery), lead_time_days: Number(form.lead), minimum_order_kg: Number(form.moq), order_multiple_kg: Number(form.multiple), recipients: form.recipients.split(",").map((value) => value.trim()).filter(Boolean), cooldown_hours: Number(form.cooldown), change_reason: form.reason }), onSuccess: () => { setNotice("New draft policy version saved. A different checker must activate it."); refresh() }, onError: (error: any) => setNotice(error?.response?.data?.detail || error.message) })
  const activate = useMutation({ mutationFn: (policy: StockPolicy) => purchaseApi.activateStockPolicy(policy.id, { expected_version: policy.version, reason: "Threshold and procurement settings reviewed" }), onSuccess: () => { setNotice("Policy activated and legacy item thresholds aligned."); refresh() }, onError: (error: any) => setNotice(error?.response?.data?.detail || error.message) })
  const evaluate = useMutation({ mutationFn: () => purchaseApi.evaluateStockAlerts(), onSuccess: ({ data }) => { setNotice(`${data.evaluated_policies} active policies evaluated; ${data.changed.length} alert episodes changed.`); refresh() } })
  const active = policies.filter((row) => row.status === "ACTIVE").length; const drafts = policies.filter((row) => row.status === "DRAFT").length
  const valid = Number(form.target) >= Number(form.reorder) && Number(form.reorder) >= Number(form.safety) && Boolean(form.item_id) && form.reason.trim().length >= 3

  return <RoleGate allow={["PlantManager", "Store"]}>
    <ProcurementShell eyebrow="Stock policy authority" title="Stock alert policies"
      description="Safety, reorder, target, lead time, MOQ and order multiple drive the same alert and MRP calculations. Previewing saves nothing and sends nothing; evaluation creates deduplicated breach episodes.">
      <RequestErrors errors={[create.error, activate.error, evaluate.error, query.error]} />
    {notice ? <MessageBar tone={notice.includes("error") || notice.includes("must") ? "error" : "success"}>{notice}</MessageBar> : null}
      <section className="grid gap-3 sm:grid-cols-3"><SummaryCard label="Active policies" value={active} detail="Effective material rules" icon={BellRing} tone="emerald" /><SummaryCard label="Draft versions" value={drafts} detail="Awaiting checker activation" icon={ShieldAlert} tone="amber" /><SummaryCard label="Precedence" value="Item → plant" detail="Deterministic effective rule" icon={Gauge} tone="cyan" /></section>
      <section className="grid gap-4 xl:grid-cols-[0.85fr_1.15fr]">
        <WorkPanel title="Draft policy version" description="All paper thresholds are canonical kg. Target must be at least reorder, which must be at least safety.">
          <div className="grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Field label="Material"><select className={fieldClass} value={form.item_id} onChange={(e) => setForm({ ...form, item_id: e.target.value })}><option value="">Select material</option>{items.map((item) => <option key={item.id} value={item.id}>{item.item_code} · {item.name}</option>)}</select></Field></div><Field label="Safety kg"><input className={fieldClass} type="number" min="0" value={form.safety} onChange={(e) => setForm({ ...form, safety: e.target.value })} /></Field><Field label="Reorder kg"><input className={fieldClass} type="number" min="0" value={form.reorder} onChange={(e) => setForm({ ...form, reorder: e.target.value })} /></Field><Field label="Target kg"><input className={fieldClass} type="number" min="0" value={form.target} onChange={(e) => setForm({ ...form, target: e.target.value })} /></Field><Field label="Recovery margin kg"><input className={fieldClass} type="number" min="0" value={form.recovery} onChange={(e) => setForm({ ...form, recovery: e.target.value })} /></Field><Field label="Lead days"><input className={fieldClass} type="number" min="0" value={form.lead} onChange={(e) => setForm({ ...form, lead: e.target.value })} /></Field><Field label="Minimum order kg"><input className={fieldClass} type="number" min="0" value={form.moq} onChange={(e) => setForm({ ...form, moq: e.target.value })} /></Field><Field label="Order multiple kg"><input className={fieldClass} type="number" min="0" value={form.multiple} onChange={(e) => setForm({ ...form, multiple: e.target.value })} /></Field><Field label="Cooldown hours"><input className={fieldClass} type="number" min="1" value={form.cooldown} onChange={(e) => setForm({ ...form, cooldown: e.target.value })} /></Field><div className="sm:col-span-2"><Field label="Recipient roles" hint="comma separated"><input className={fieldClass} value={form.recipients} onChange={(e) => setForm({ ...form, recipients: e.target.value })} /></Field></div><div className="sm:col-span-2"><Field label="Required change reason"><input className={fieldClass} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} placeholder="Why these thresholds are being introduced or changed" /></Field></div></div>
          <div className="mt-4 rounded-lg border border-signal-cyan-line bg-signal-cyan-soft p-4 text-sm text-signal-cyan-ink"><p className="font-semibold">Preview only</p><p className="mt-1">Critical at ≤ {Number(form.safety).toLocaleString("en-IN")} kg · warning at ≤ {Number(form.reorder).toLocaleString("en-IN")} kg · recover above {(Number(form.reorder) + Number(form.recovery)).toLocaleString("en-IN")} kg.</p></div>
          <button className={`${primaryButton} mt-4 w-full`} disabled={!valid || create.isPending} onClick={() => create.mutate()}><Save className="h-4 w-4" /> Save draft policy</button>
        </WorkPanel>
        <WorkPanel title="Policy version register" description="Draft and active versions remain visible for audit. Activation also aligns existing item reorder fields.">
          {query.isLoading ? <div className="h-40 animate-pulse rounded-lg bg-muted" /> : policies.length ? <div className="space-y-3">{policies.map((policy) => <article key={policy.id} className="rounded-xl border border-border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-foreground">{policy.item_code || policy.item_id} · {policy.item_name}</p><p className="mt-1 text-xs text-muted-foreground">Version {policy.version} · {policy.stock_basis.replaceAll("_", " ").toLowerCase()} · created {policy.created_by}</p></div><StateBadge value={policy.status} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-muted p-2"><p className="text-[9px] font-bold uppercase text-muted-foreground">Safety</p><p className="mt-1 font-semibold tabular-nums">{policy.safety_stock_kg} kg</p></div><div className="rounded-lg bg-muted p-2"><p className="text-[9px] font-bold uppercase text-muted-foreground">Reorder</p><p className="mt-1 font-semibold tabular-nums">{policy.reorder_point_kg} kg</p></div><div className="rounded-lg bg-muted p-2"><p className="text-[9px] font-bold uppercase text-muted-foreground">Target</p><p className="mt-1 font-semibold tabular-nums">{policy.target_stock_kg} kg</p></div></div>{policy.status === "DRAFT" ? <button className={`${secondaryButton} mt-3`} disabled={activate.isPending} onClick={() => activate.mutate(policy)}><CheckCircle2 className="h-4 w-4" /> Activate as checker</button> : null}</article>)}</div> : <EmptyState label="No stock policy versions. Save the first material policy." />}
        </WorkPanel>
      </section>
      <WorkPanel title="Alert evaluator" description="Evaluation is an explicit server action. Repeated checks update one episode; they do not create duplicate alerts."><button className={primaryButton} disabled={evaluate.isPending || !active} onClick={() => evaluate.mutate()}><BellRing className="h-4 w-4" /> Evaluate active policies now</button><Link href="/inventory/stock-alerts" className={`${secondaryButton} ml-2`}>Open alert inbox</Link></WorkPanel>
    </ProcurementShell>
  </RoleGate>
}
