const { test, expect } = require('@playwright/test')
const { getBrowserFixture, getRuntimeManifest, requireCredential, beginCriticalMonitoring } = require('./_runtime-data.cjs')

test('whole customer PO calendar preserves partial releases, dated splits and reviewed revision', async ({ page }) => {
  const fixture = getBrowserFixture()
  const bff = getRuntimeManifest().urls.bff
  if (!['localhost', '127.0.0.1'].includes(new URL(bff).hostname)) throw new Error('Mutating acceptance requires an isolated local stack')
  const catalog = fixture.catalog.plant_a
  const headers = { 'X-Plant-ID': fixture.plants.plant_a.id }
  const check = beginCriticalMonitoring(page)
  async function login(key) {
    await page.context().clearCookies()
    const user = requireCredential(key)
    const result = await page.request.post(`${bff}/api/auth/login`, { data: { email: user.email, password: user.password } })
    expect(result.ok()).toBeTruthy()
  }
  async function post(path, data) {
    const response = await page.request.post(`${bff}/api/sales/${path}`, { headers, data })
    expect(response.ok(), await response.text()).toBeTruthy()
    return response.json()
  }
  await page.goto('/login')
  await login('sales_maker_a')
  const order = await post('orders', {
    customer_id: catalog.customer.id, origin: 'CUSTOMER_PO', po_number: `CALENDAR-${Date.now()}`, po_date: '2026-09-01',
    lines: [100, 80].map((qty, index) => ({ approved_spec_id: catalog.approved_spec_id, line_no: index + 1, product_code: `CAL-L${index + 1}`, qty, due_date: '2026-12-31' })),
  })
  await login('sales_approver_a')
  await post(`orders/${order.id}/approve`, {})
  const released = await post(`orders/lines/${order.lines[0].id}/release`, { release_qty: 20, winder_machine_id: catalog.winder_ids[0] })
  await page.evaluate(id => localStorage.setItem('hariom_active_plant', id), fixture.plants.plant_a.id)
  await page.goto(`/sales-orders/${order.id}`)
  const panel = page.getByTestId('delivery-schedule-panel')
  await expect(panel).toBeVisible()
  await panel.getByLabel('Default delivery date', { exact: true }).fill('2026-12-15')
  await panel.getByRole('button', { name: 'Add date split' }).first().click()
  await panel.getByRole('spinbutton', { name: /CAL-L1.*split 1 quantity/ }).fill('40')
  await panel.getByRole('button', { name: 'Add date split' }).first().click()
  await panel.getByLabel(/CAL-L1.*split 2 date/).fill('2026-12-22')
  await expect(panel.getByRole('spinbutton', { name: /CAL-L1.*split 2 quantity/ })).toHaveValue('60')
  await panel.getByTestId('schedule-entire-po:preview').click()
  await expect(panel.getByTestId('schedule-entire-po:commit')).toBeEnabled()
  await expect(panel.getByTestId('schedule-entire-po:preview-body')).toContainText('80 pcs')
  // Any edit invalidates the exact proposal the user reviewed.
  await panel.getByLabel('Default delivery date', { exact: true }).fill('2026-12-16')
  await expect(panel.getByTestId('schedule-entire-po:commit')).toBeDisabled()
  await panel.getByTestId('schedule-entire-po:preview').click()
  await expect(panel.getByTestId('schedule-entire-po:commit')).toBeEnabled()
  await panel.getByTestId('schedule-entire-po:commit').click()
  await expect(panel.locator('[data-testid^="delivery-schedule-row:"]')).toHaveCount(3)
  await page.reload()
  await expect(panel.locator('[data-testid^="delivery-schedule-row:"]')).toHaveCount(3)
  const response = await page.request.get(`${bff}/api/sales/orders/${order.id}/delivery-schedules`, { headers })
  expect(response.ok()).toBeTruthy()
  const saved = await response.json()
  expect(saved.items.reduce((total, row) => total + row.quantity, 0)).toBe(180)
  expect(saved.items.map(row => row.delivery_date).sort()).toEqual(['2026-12-15', '2026-12-16', '2026-12-22'])
  const afterResponse = await page.request.get(`${bff}/api/sales/orders/${order.id}`, { headers })
  expect(afterResponse.ok()).toBeTruthy()
  const after = await afterResponse.json()
  expect(after.lines[0].released_qty).toBe(20)
  expect(after.lines[0].release_lots[0].id || after.lines[0].release_lots[0].release_lot_id).toBe(released.id)
  await panel.getByLabel('Delivery calendar month', { exact: true }).fill('2026-12')
  const protectedRow = saved.items.find(row => row.delivery_date === '2026-12-15')
  const locked = await page.request.patch(`${bff}/api/sales/orders/${order.id}/delivery-schedules/${protectedRow.id}`, { headers, data: { status: 'locked' } })
  expect(locked.ok(), await locked.text()).toBeTruthy()
  await page.reload()
  await panel.getByLabel('Shift by days', { exact: true }).fill('2')
  await panel.getByRole('button', { name: 'Preview date shift', exact: true }).click()
  await expect(panel.getByTestId('delivery-shift-preview')).toContainText('preserved')
  const unchanged = await page.request.get(`${bff}/api/sales/orders/${order.id}/delivery-schedules`, { headers })
  expect((await unchanged.json()).items.map(row => row.delivery_date).sort()).toEqual(['2026-12-15', '2026-12-16', '2026-12-22'])
  await panel.getByRole('button', { name: 'Save date shift', exact: true }).click()
  await expect(panel.getByTestId('delivery-shift-preview')).toHaveCount(0)
  await page.reload()
  const shifted = await page.request.get(`${bff}/api/sales/orders/${order.id}/delivery-schedules`, { headers })
  const shiftData = await shifted.json()
  expect(shiftData.items.map(row => row.delivery_date).sort()).toEqual(['2026-12-15', '2026-12-18', '2026-12-24'])
  expect(shiftData.items.reduce((total, row) => total + row.quantity, 0)).toBe(180)
  await panel.getByLabel('Delivery calendar month', { exact: true }).fill('2026-12')
  await page.screenshot({ path: `${process.env.PLAYWRIGHT_OUTPUT_DIR}/whole-customer-po-calendar.png`, fullPage: true })
  await check()
})
