const { test, expect } = require('@playwright/test')
const { getBrowserFixture, getRuntimeManifest, beginCriticalMonitoring } = require('./_runtime-data.cjs')

async function signIn(page) {
  const fixture = getBrowserFixture()
  await page.goto('/login')
  const result = await page.request.post(`${getRuntimeManifest().urls.bff}/api/auth/login`, {
    data: { email: fixture.auth.admin_email, password: fixture.auth.admin_password },
  })
  expect(result.ok(), await result.text()).toBeTruthy()
  await page.evaluate(id => localStorage.setItem('hariom_active_plant', id), fixture.plants.plant_a.id)
}

test('saved monthly calendar conserves an entered arrival through reload and workbook grid', async ({ page }) => {
  const check = beginCriticalMonitoring(page)
  await signIn(page)
  await page.goto('/purchase/scheduler')
  await expect(page.getByRole('heading', { name: 'Paper purchase planner' })).toBeVisible()
  await Promise.all([page.waitForResponse(response => response.url().includes('/api/purchase/v2/plans?month=2026-12-01') && response.ok()), page.getByLabel('Month', { exact: true }).fill('2026-12')])
  const create = page.getByRole('button', { name: 'Create month plan' })
  await expect(page.getByRole('button', { name: 'Plan arrivals 2026-12-31' })).toBeVisible()
  if (await create.isEnabled()) await create.click()
  const lane = page.getByRole('combobox', { name: 'Add material lane', exact: true })
  await expect(lane).toBeEnabled()
  const choices = await lane.locator('option').evaluateAll(nodes => nodes.filter(n => n.value).map(n => ({ value: n.value, text: n.textContent })))
  if (choices.length) await lane.selectOption(choices[0].value)
  await page.getByRole('button', { name: 'Plan arrivals 2026-12-15' }).click()
  const quantity = page.getByRole('spinbutton', { name: / kg$/ }).filter({ visible: true }).first()
  await quantity.fill('123.456')
  await page.getByRole('button', { name: 'Save calendar', exact: true }).filter({ visible: true }).click()
  await expect(page.getByText('All daily kg entries and import evidence saved with a new plan version.')).toBeVisible()
  await page.reload()
  await page.getByLabel('Month', { exact: true }).fill('2026-12')
  await page.getByRole('button', { name: 'Plan arrivals 2026-12-15' }).click()
  await expect(page.getByRole('spinbutton', { name: / kg$/ }).filter({ visible: true }).first()).toHaveValue('123.456')
  await page.getByRole('button', { name: 'Workbook grid', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Monthly grid', exact: true })).toBeVisible()
  await check()
})

test('client workbook previews with explicit units and never imports helper vehicle counts', async ({ page }) => {
  const check = beginCriticalMonitoring(page)
  if (!process.env.ERP_REFERENCE_WORKBOOK) throw new Error('Set ERP_REFERENCE_WORKBOOK to the client reference workbook')
  await signIn(page)
  await page.goto('/purchase/scheduler')
  await page.getByLabel('Month', { exact: true }).fill('2026-09')
  await page.getByLabel('Import Excel', { exact: true }).setInputFiles(process.env.ERP_REFERENCE_WORKBOOK)
  await expect(page.getByText(/Workbook preview:/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Stage mapped cells as kg' })).toBeDisabled()
  await expect(page.getByLabel(/^Map VEHI/i)).toHaveCount(0)
  await expect(page.getByLabel(/Workbook quantity unit/)).toHaveValue('')
  await page.screenshot({ path: `${process.env.PLAYWRIGHT_OUTPUT_DIR}/client-workbook-preview.png`, fullPage: true })
  await check()
})
