const {test,expect}=require('@playwright/test')
const {getBrowserFixture,getRuntimeManifest,requireCredential}=require('./_runtime-data.cjs')
const routes=['/dashboard','/landing/owner','/sales-orders','/sales-orders/pending','/planning/board','/production/job-cards','/quality','/purchase','/purchase/scheduler','/purchase/receipts','/inventory','/logistics/dispatch','/analytics','/masters/papers','/system/users','/help']
async function login(page,key="admin"){
 const fixture=getBrowserFixture(),user=requireCredential(key)
 await page.goto('/login')
 const response=await page.request.post(`${getRuntimeManifest().urls.bff}/api/auth/login`,{data:{email:user.email,password:user.password}})
 expect(response.status()).toBe(200)
 await page.evaluate(id=>localStorage.setItem('hariom_active_plant',id),fixture.plants.plant_a.id)
}
test('redesign route and viewport evidence',async({page})=>{
 test.setTimeout(240000)
 await login(page)
 for(const theme of ['light','dark']){
  await page.evaluate(value=>localStorage.setItem('hariom_theme_v1',value),theme)
  for(const route of routes){
   await page.setViewportSize({width:1440,height:1000})
   await page.goto(route,{waitUntil:'networkidle'})
   await expect(page.locator('.tube-shell')).toBeVisible()
   await expect(page).toHaveURL(route === '/dashboard' ? /\/landing\/(owner|admin)$/ : new RegExp(route.replaceAll('/', '\\/')+'(?:\\?.*)?$'))
   await expect(page.locator('html')).toHaveAttribute('data-theme',theme)
   expect.soft(await page.evaluate(()=>document.documentElement.scrollWidth),`${route} ${theme} document overflow`).toBeLessThanOrEqual(1440)
   await page.screenshot({path:`${process.env.PLAYWRIGHT_OUTPUT_DIR}/${theme}${route.replaceAll('/','_')}.png`,fullPage:false})
  }
  for(const width of [320,390,768,1024]){
   await page.setViewportSize({width,height:1000})
   await page.goto('/purchase/receipts',{waitUntil:'networkidle'})
   await expect(page.locator('.tube-shell')).toBeVisible()
   await expect(page).toHaveURL(/purchase\/receipts/)
   expect.soft(await page.evaluate(()=>document.documentElement.scrollWidth),`Receipt register ${theme} at ${width}px`).toBeLessThanOrEqual(width)
   await page.screenshot({path:`${process.env.PLAYWRIGHT_OUTPUT_DIR}/${theme}-receipts-${width}.png`,fullPage:false})
  }
 }
})
test('theme persistence, deliberate navigation resize, command keyboard and mobile focus',async({page})=>{
 await login(page)
 await page.setViewportSize({width:1440,height:1000})
 await page.goto('/purchase')
 await page.getByRole('button',{name:'Appearance settings',exact:true}).click()
 await page.getByRole('group',{name:'Theme',exact:true}).getByRole('button',{name:'Dark',exact:true}).click()
 await page.keyboard.press('Escape')
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await page.reload()
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
 await page.getByRole('button',{name:'Collapse navigation',exact:true}).click()
 await expect(page.locator('.tube-shell')).toHaveAttribute('data-rail','compact')
 // Transition completion is observed, then pointer movement must not resize content.
 await expect.poll(async()=>(await page.locator('main').boundingBox()).x).toBe(64)
 const before=(await page.locator('main').boundingBox()).x
 await page.locator('.tube-rail').hover()
 expect((await page.locator('main').boundingBox()).x).toBe(before)
 await page.keyboard.press('Control+k')
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.getByRole('textbox',{name:'Find workspace'}).fill('incoming qc')
 await page.keyboard.press('Enter')
 await expect(page).toHaveURL(/quality\/incoming/)
 await page.setViewportSize({width:390,height:900})
 const trigger=page.getByRole('button',{name:'Open workspace navigation'})
 await trigger.click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await page.keyboard.press('Escape')
 await expect(page.getByRole('dialog')).toHaveCount(0)
 await expect(trigger).toBeFocused()
})
test('purchase register keeps filter and server paging in a shareable URL',async({page})=>{
 await login(page)
 await page.goto('/purchase?size=10&page=1')
 await page.getByRole('textbox',{name:'Search purchase orders'}).fill('MIXED')
 await expect(page).toHaveURL(/q=MIXED/)
 await expect(page.getByRole('navigation',{name:'Pagination'})).toBeVisible()
 await page.getByRole('combobox',{name:'Rows per page'}).selectOption('25')
 await expect(page).toHaveURL(/size=25/)
 await page.reload()
 await expect(page.getByRole('textbox',{name:'Search purchase orders'})).toHaveValue('MIXED')
 await expect(page.getByRole('combobox',{name:'Rows per page'})).toHaveValue('25')
})
test('help search, responsive handbook and downloadable PDF stay available',async({page})=>{
 await login(page)
 await page.setViewportSize({width:390,height:900})
 await page.goto('/help')
 await expect(page.locator('.tube-shell')).toBeVisible()
 await page.getByRole('textbox',{name:'Search guides'}).fill('Customer PO')
 await page.getByTestId('guide-index:customer-calendar').click()
 await expect(page.getByRole('heading',{name:'Customer PO Calendar Guide',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
 const pdf=await page.request.get('/docs/Hari-Om-TubeOS-Client-Guide.pdf')
 expect(pdf.status()).toBe(200)
 expect((await pdf.body()).subarray(0,5).toString()).toBe('%PDF-')
 await page.goto('/docs/Hari-Om-TubeOS-Client-Guide.html')
 await expect(page.getByRole('heading',{name:'A clearer way to run every stage.'})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
 await page.getByRole('searchbox',{name:'Find a workflow'}).fill('supplier promises')
 await expect(page.locator('nav a:visible')).not.toHaveCount(0)
 await page.screenshot({path:`${process.env.PLAYWRIGHT_OUTPUT_DIR}/client-guide-mobile.png`})
})
test('dedicated planning pages keep stage, date and focused-order context',async({page})=>{
 await login(page)
 await page.goto('/planning/winder?plan_date=2026-09-22&order_id=design-context-check')
 await expect(page.getByTestId('planner-page')).toContainText(/winder planner/i)
 await page.getByRole('combobox',{name:'Planning workspace',exact:true}).selectOption('oven')
 await expect(page).toHaveURL(/\/planning\/oven\?/)
 await expect(page).toHaveURL(/plan_date=2026-09-22/)
 await expect(page).toHaveURL(/order_id=design-context-check/)
 await expect(page.getByRole('combobox',{name:'Planning workspace',exact:true})).toHaveValue('oven')
 await page.getByRole('link',{name:'Planning overview',exact:true}).click()
 await expect(page).toHaveURL(/\/planning\/overview$/)
 await expect(page.getByRole('combobox',{name:'Planning workspace',exact:true})).toHaveValue('summary')
})

test('planner role can discover its dedicated stage pages in command search',async({page})=>{
 await login(page,'planner_a')
 await page.goto('/planning/winder')
 await expect(page.locator('.tube-shell')).toBeVisible()
 await page.keyboard.press('Control+k')
 await page.getByRole('textbox',{name:'Find workspace'}).fill('Oven planning')
 await page.getByRole('button',{name:/^Oven planning/}).click()
 await expect(page).toHaveURL(/\/planning\/oven$/)
 await expect(page.getByRole('combobox',{name:'Planning workspace',exact:true})).toHaveValue('oven')
})
