from pathlib import Path
import json,html,re,shutil,subprocess
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,PageBreak,KeepTogether,ListFlowable,ListItem,Table,TableStyle
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
root=Path(__file__).resolve().parents[2]; out=root/'apps/web-ui/public/docs';out.mkdir(parents=True,exist_ok=True)
guides=json.loads(subprocess.check_output(['node','-r','./node_modules/sucrase/register','-e',"process.stdout.write(JSON.stringify(require('./lib/guide-content.ts').getAllGuides()))"],cwd=root/'apps/web-ui',text=True))
changes=[
('Workspace navigation','Hover-dependent navigation and crowded module tabs.','An explicit compact or expanded rail, grouped workspaces, a keyboard command menu, and a mobile navigation dialog. Planning has dedicated overview, winder, oven, process and slitting pages; reconciliation has workspace, actuals, drift and history pages.'),
('Appearance and comfort','Mixed panel styles, oversized headers and hard-coded light colors.','Pearl surfaces, ink text and teal actions; semantic status colors; Light, Dark and System appearance; compact table density; bounded motion and reduced-motion support.'),
('Page structure','Large decorative headers competed with operational information.','Compact page headers, clear actions, consistent summaries, filters, registers and detail panels. Existing business actions and permissions are retained.'),
('Customer PO scheduling','Pending demand and scheduling needed a unified whole-order flow.','Review pending customer orders, required quantities and material demand. Preview a whole-PO customer delivery schedule, inspect dated quantities, then save the reviewed version. Schedule production separately on machine and shift capacity slots. Split allocations and stale previews remain explicit.'),
('Monthly procurement calendar','The client workbook workflow was absent from the recovered checkout.','A monthly material schedule supports item-specific demand, frozen job BOMs, accepted external finished goods and supplier arrivals. A reviewed workbook preview is required before applying changes.'),
('Supplier promises','Delivery promises and receipts needed a common history.','Supplier schedule allocations link promised deliveries, receipt allocation and history. Future confirmed supply is separated from available stock.'),
('Purchase approval','Changes to vendor terms needed durable review evidence.','Multi-item purchase orders use numbered documents, revision snapshots and maker-checker approval. Changes after approval require a new reviewed revision.'),
('Purchase register','Browser-side filtering could miss orders beyond a fetched page.','Search and paging run on the server. The shareable URL keeps query, status, page and size. Matching-order summaries cover all filtered results and keep units separate.'),
('Material inward','Receipt entry needed both PO-backed and manual flows.','Manual and PO-backed GRNs retain material identity, measured reels/coils, invoice evidence and stock batch links. ALL-plant scope is read-only for plant-specific execution.'),
('Commercial differences','Invoice rates and approved PO rates could be confused.','Commercial differences, debit-note actions and historical batch costs remain distinct from QC disposition. An invoice disagreement is not a quality release.'),
('Labels and registers','Operators needed durable source identity in outputs.','AT/QR labels, receipt details and register exports retain document and lot context. Mixed-unit quantities and rates are displayed with their own units.'),
('Quality controls','Quality criteria and stock disposition needed linked evidence.','Available QC flows connect incoming and stage inspection, frozen lot criteria, measurements and hold/disposition. Packing measurements cannot substitute for final QC; dispatch independently requires a current passing final inspection. Approved criteria may be marked Critical: cannot be waived. Their frozen policy blocks administrator concessions and stage overrides after failure. The release appendix identifies remaining advanced quality and race-condition checks.'),
('Dashboard meaning','Some displayed targets and sparklines were not supported by the metric.','The owner dashboard removes the assumed 92% OTIF target and quantity sparklines from currency metrics. Loading, unavailable and failed data are visible; cards link to relevant workspaces.'),
('Winder release and planning','Winder capability checks could stop scheduling on an otherwise available machine.','Select a winder number or name at release as a hint. Planning and execution show geometry or mandrel advisories without blocking; plant, availability, capacity and QC controls remain. Large quantities split across capacity slots.'),
('BOM geometry and dispatch dates','Material calculations could use sample dimensions and zero inner diameter; dispatch without a date could use the previous UTC day.','New BOM calculations use saved specification geometry, preserve fractional lengths and honor saved nominal dimensions. New dispatches freeze the India business date for the challan and inventory posting; retries retain that date. Existing frozen jobs and historical transactions are not rewritten.'),
('Partial dispatch and phone entry','A partial shipment could fall back to the full packed quantity, and sealing could enter a URL redirect loop.','Sealing honors the entered shipment quantity, accepts the UI URL directly, and preserves retry identity. The phone form stacks customer, transport and item details; printed challans retain their document layout.'),
('Help and handover','Help did not explain all recovered flows or new controls.','A searchable guide library, route-specific instructions and matching downloadable HTML/PDF cover operator steps, field rules, controls and outputs.'),
]
status='Review edition · 22 September 2026 · Local implementation candidate'
intro='This guide describes the recovered and redesigned Hari Om TubeOS candidate. It is not evidence that the candidate is deployed to AWS or that every requested acceptance case has passed. Use the release checklist at the end before client sign-off.'
limits=[
'Python 3.11 authentication crashes were reproduced. The candidate is pinned to Python 3.12.14, which passed direct and BFF concurrency checks. Verify the exact deployed interpreter and complete release acceptance; an earlier diagnostic runtime is not the deployment target.',
'AWS deployment, live schema reconciliation, backup/restore rehearsal and signed-in production acceptance are pending.',
'The inherited functional acceptance catalogue still contains partial, limited and not-run cases. Earlier recovery test counts do not certify this redesign.',
'Critical non-waivable criteria now block administrator concessions, hold release and inline stage overrides. Further acceptance remains for corrective reinspection recovery, linked rework/reheat and material attribution, partial customer returns, corrective actions, escalation coverage and cross-service hold/release races.',
'A linked 64-piece synthetic order passed local calendar, cross-winder split, production, final QC and dispatch checks. A second order passed two 32-piece shipments through phone and desktop UI, replay checks, challan PDF generation and exact stock reconciliation. Client-witnessed production, real measurements and physical output acceptance remain pending; local test data is not client acceptance.',
'Client-approved QC limits, physical printing, mobile device acceptance and representative workload testing remain required. Server paging of the purchase register does not establish unlimited scale across every module.',
]
acceptance=[
('Identity and scope','Sign in with each client role. Verify allowed workspaces, a specific plant, ALL-plant read views, expired sessions and access changes.'),
('Customer demand to calendar','Select a real pending PO. Reconcile its quantities and BOM with the client workbook; preview and save allocations; reopen them; check partial, split, stale and over-capacity cases.'),
('Procurement to stock','Create and independently approve a mixed-item PO; revise it; record partial receipts with measured lots and invoice differences; reconcile promised, received, short-closed and outstanding quantities.'),
('Quality and exceptions','Approve client criteria; inspect each required stage; prove held stock cannot be issued or dispatched; record disposition and authorization. Close the outstanding advanced QC gaps before claiming full-cycle acceptance.'),
('Production to dispatch','Trace the same order through material issue, output, waste/variance, QC release, packing and dispatch. Reconcile quantities and source identity at every handoff.'),
('Experience and operations','Use real desktop, tablet and phone devices; keyboard-only dialogs; long registers and exports; label printer and PDFs. Exercise backup/restore and verify the exact deployed version.'),
]
def esc(x):return html.escape(str(x))
def lis(xs):return '<ul>'+''.join('<li>'+esc(x)+'</li>' for x in xs)+'</ul>'
sections=[]
sections.append('<section id="changes"><p class="eyebrow">Change comparison</p><h2>What changed and why</h2><div class="changes">'+''.join('<article><h3>'+esc(t)+'</h3><p class="label">Previous issue</p><p>'+esc(a)+'</p><p class="label">Candidate behavior</p><p>'+esc(b)+'</p></article>' for t,a,b in changes)+'</div></section>')
for i,g in enumerate(guides,1):
 steps='<ol class="steps">'+''.join('<li><h3>'+esc(s['label'])+'</h3><p>'+esc(s['detail'])+'</p></li>' for s in g['steps'])+'</ol>'
 panels=''.join('<article><h3>'+label+'</h3>'+lis(g[key])+'</article>' for key,label in [('fieldRules','Field rules'),('primaryActions','Actions'),('controlChecks','Control checks'),('outputs','Expected outputs')])
 sections.append(f'<section id="{esc(g["id"])}" data-guide><p class="eyebrow">{i:02d} / {esc(g["eyebrow"])}</p><h2>{esc(g["title"])}</h2><p class="route">Workspace: {esc(g["route"])}</p><p class="lead">{esc(g["summary"])}</p><h3>{esc(g["flowTitle"])}</h3>{steps}<div class="panels">{panels}</div><p class="related">Related workspaces: '+ ' · '.join(esc(x) for x in g['relatedRoutes'])+'</p></section>')
sections.append('<section id="release"><p class="eyebrow">Client review and release</p><h2>Acceptance before sign-off</h2><p>'+esc(intro)+'</p><h3>Outstanding release gates</h3>'+lis(limits)+'<h3>Witnessed acceptance checklist</h3>'+''.join('<article class="check"><h3>□ '+esc(t)+'</h3><p>'+esc(v)+'</p><p class="sign">Evidence / reviewer / date: ___________________________________</p></article>' for t,v in acceptance)+'</section>')
nav='<a href="#changes">What changed</a>'+''.join(f'<a href="#{esc(g["id"])}">{esc(g["title"])}</a>' for g in guides)+'<a href="#release">Release checklist</a>'
css='''*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f7f6;color:#203139;font:15px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:#17645f}header{padding:64px max(24px,calc((100vw - 1200px)/2));background:#173c3b;color:#fff}header h1{max-width:800px;font-size:clamp(34px,5vw,58px);line-height:1.1;letter-spacing:-.045em;margin:18px 0}header p{max-width:780px;color:#d6e6e3}.eyebrow,.label{font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#37726d}.edition{font-size:12px;color:#b9d4cf}.layout{display:grid;grid-template-columns:240px minmax(0,1fr);gap:40px;max-width:1280px;margin:auto;padding:32px 24px}aside{position:sticky;top:20px;align-self:start;max-height:95vh;overflow:auto}aside input{width:100%;padding:12px;border:1px solid #ccd7d4;border-radius:8px;background:#fff;font:inherit}nav{display:grid;margin-top:16px}nav a{padding:8px 10px;font-size:13px;text-decoration:none;border-radius:6px}nav a:hover,nav a:focus-visible{background:#e2eeea}section{scroll-margin-top:24px;margin-bottom:30px;padding:32px;border:1px solid #dce4e1;border-radius:16px;background:#fff}h2{font-size:30px;line-height:1.2;letter-spacing:-.03em;margin:10px 0 18px}h3{font-size:17px;line-height:1.4;margin:20px 0 8px}.route{font:12px ui-monospace,monospace;color:#5b746d;overflow-wrap:anywhere}.lead{font-size:17px;color:#4d625d}.changes,.panels{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.changes article,.panels article{padding:18px;background:#f6f8f7;border-radius:10px}.changes h3,.panels h3{margin-top:0}.label{margin-bottom:4px}.label+p{margin-top:0;font-size:14px}ul{padding-left:20px}li{margin:8px 0}.steps{padding-left:26px}.steps li{padding-left:8px;margin:20px 0}.steps h3{margin:0}.steps p{margin:5px 0}.related{padding-top:18px;border-top:1px solid #dce4e1;font-size:12px;overflow-wrap:anywhere}.check{border-bottom:1px solid #dce4e1;padding:10px 0 20px}.sign{color:#70817a;font-size:12px}footer{padding:30px;text-align:center;color:#63766f;font-size:12px}[hidden]{display:none!important}button{padding:10px 16px;border:1px solid #bfd3cc;border-radius:8px;background:white;color:#204942;cursor:pointer}@media(max-width:850px){.layout{display:block;padding:16px}aside{position:static;max-height:260px;margin-bottom:24px}section{padding:22px}.panels,.changes{grid-template-columns:1fr}header{padding:36px 24px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}@media print{body{background:white;font-size:10pt}header{background:white;color:#173c3b;padding:0}header p,.edition{color:#536c64}aside,button{display:none}.layout{display:block;padding:0}section{border:0;border-radius:0;break-before:page;padding:0}.changes article,.panels article{break-inside:avoid}h2,h3{break-after:avoid}footer{display:none}}'''
doc='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Hari Om TubeOS | Client workflow guide</title><style>'+css+'</style></head><body><header><div class="edition">HARI OM PAPER / TUBEOS</div><h1>A clearer way to run every stage.</h1><p>Client workflow guide and change comparison</p><p class="edition">'+esc(status)+'</p><p>'+esc(intro)+'</p><button onclick="window.print()">Print this guide</button></header><div class="layout"><aside aria-label="Guide contents"><label for="search">Find a workflow</label><input id="search" type="search" placeholder="Search guide contents"><nav>'+nav+'</nav></aside><main>'+''.join(sections)+'</main></div><footer>Hari Om Paper · TubeOS · Review edition · '+str(len(guides))+' workflow guides</footer><script>document.querySelector("#search").addEventListener("input",e=>{const q=e.target.value.toLowerCase().trim();document.querySelectorAll("nav a").forEach(a=>{const s=document.querySelector(a.getAttribute("href"));a.hidden=q&&!s.textContent.toLowerCase().includes(q)})})</script></body></html>'
(out/'Hari-Om-TubeOS-Client-Guide.html').write_text(doc)
styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='Cover',fontName='Helvetica-Bold',fontSize=34,leading=39,textColor=colors.HexColor('#173c3b'),spaceAfter=24));styles.add(ParagraphStyle(name='Title2',fontName='Helvetica-Bold',fontSize=23,leading=28,textColor=colors.HexColor('#173c3b'),spaceAfter=14));styles.add(ParagraphStyle(name='Kicker',fontSize=9,leading=13,textColor=colors.HexColor('#39766b'),spaceAfter=12));styles['BodyText'].fontSize=9.5;styles['BodyText'].leading=12.5;styles['BodyText'].spaceAfter=4;styles['Heading3'].fontSize=11;styles['Heading3'].leading=13;styles['Heading3'].textColor=colors.HexColor('#1b6259');styles['Heading3'].spaceBefore=6
flow=[]
def clean(s):return s.replace('·',' / ').replace('—','-').replace('–','-').replace('’',"'").replace('“','"').replace('”','"')
def p(s,style='BodyText'):return Paragraph(esc(clean(s)),styles[style])
def bullet(s):return Paragraph('- '+esc(clean(s)),styles['BodyText'])
flow +=[Spacer(1,68),p('HARI OM PAPER / TUBEOS','Kicker'),p('A clearer way to run every stage.','Cover'),p('Client workflow guide and change comparison','Title2'),p(status,'Kicker'),Spacer(1,20),p(intro),Spacer(1,25),p('How to use this guide','Heading3'),p('Start with the change comparison. Find your workflow in the contents, follow its steps and confirm the expected output. Use the final checklist to compare the candidate against the client requirement before accepting a release.'),p('Document paths and page names refer to this candidate. Access is controlled by your assigned role and plant; some workspaces may not appear for every user.'),PageBreak(),p('Contents','Title2'),p('Change comparison','Kicker')]
for i,g in enumerate(guides,1):flow.append(p(f'{i:02d}. {g["title"]}'))
flow.append(p('Client acceptance and outstanding release gates','Heading3'))
for index in range(0,len(changes),4):
 flow +=[PageBreak(),p('CHANGE COMPARISON','Kicker'),p('What changed and why','Title2')]
 for title,old,new in changes[index:index+4]:flow +=[p(title,'Heading3'),p('Previous issue: '+old),p('Candidate behavior: '+new)]
for i,g in enumerate(guides,1):
 flow +=[PageBreak(),p(f'{i:02d} / {g["eyebrow"]}','Kicker'),p(g['title'],'Title2'),p('Workspace: '+g['route'],'Kicker'),p(g['summary']),p(g['flowTitle'],'Heading3')]
 for k,step in enumerate(g['steps'],1):flow.append(p(f'{k}. {step["label"]}: {step["detail"]}'))
 for key,label in [('fieldRules','Field rules'),('primaryActions','Actions'),('controlChecks','Control checks'),('outputs','Expected outputs')]:
  flow.append(p(label,'Heading3'));flow.extend(bullet(v) for v in g[key])
 flow.append(p('Related: '+' / '.join(g['relatedRoutes']),'Kicker'))
flow +=[PageBreak(),p('CLIENT REVIEW AND RELEASE','Kicker'),p('Acceptance before sign-off','Title2'),p(intro),p('Outstanding release gates','Heading3')]+[bullet(s) for s in limits]
flow +=[PageBreak(),p('Witnessed acceptance checklist','Title2')]
for t,v in acceptance:flow +=[p(t,'Heading3'),p(v),p('Evidence / reviewer / date: ___________________________________')]
def page_footer(c,d):
 c.setStrokeColor(colors.HexColor('#dce4e1'));c.line(44,42,A4[0]-44,42);c.setFont('Helvetica',8);c.setFillColor(colors.HexColor('#63766f'));c.drawString(44,28,'Hari Om TubeOS / Review edition / 22 September 2026');c.drawRightString(A4[0]-44,28,str(d.page))
pdf=out/'Hari-Om-TubeOS-Client-Guide.pdf';SimpleDocTemplate(str(pdf),pagesize=A4,rightMargin=44,leftMargin=44,topMargin=44,bottomMargin=56,title='Hari Om TubeOS - Client workflow guide',author='Hari Om Paper').build(flow,onFirstPage=page_footer,onLaterPages=page_footer)
final=root/'output/pdf';final.mkdir(parents=True,exist_ok=True);shutil.copy2(pdf,final/pdf.name)
print(json.dumps({'guides':len(guides),'pdf':str(pdf),'html':str(out/'Hari-Om-TubeOS-Client-Guide.html'),'pdf_bytes':pdf.stat().st_size}))
