"use client"
import { useEffect, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { useAuth } from "@/context/AuthContext"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { command, errorText, qcRangeLabel, seasonApi as defaultSeasonApi, seasonApiForPlant, seasonLabel, type Season } from "@/lib/season-api"

export function SeasonRecipeManager({ specId, plantId, onLoadRows }: { specId: string; plantId?:string; onLoadRows?: (rows: any) => void }) {
  const seasonApi=plantId?seasonApiForPlant(plantId):defaultSeasonApi
  const { user } = useAuth()
  const canEdit = [user?.role, ...(user?.roles || [])].some(r => r === "Owner" || r === "Admin")
  const cache = useQueryClient()
  const papers = useQuery({queryKey:["season-papers",plantId],queryFn:async()=>(await seasonApi.papers()).data})
  const [season, setSeason] = useState<Season>("ROY")
  const [editing, setEditing] = useState(false)
  const [layers, setLayers] = useState<any[]>([])
  const [note, setNote] = useState("")
  const [error, setError] = useState("")
  const [showHistory, setShowHistory] = useState(false)
  const document = useQuery({ queryKey: ["season-spec-document", specId], queryFn: async () => (await seasonApi.document(specId)).data })
  const qc = useQuery({ queryKey: ["season-spec-qc", specId, season], queryFn: async () => (await seasonApi.resolved(specId, season)).data })
  const history = useQuery({ queryKey: ["season-recipe-history", specId, season], queryFn: async () => (await seasonApi.recipeHistory(specId, season)).data, enabled: showHistory })
  const recipe = document.data?.recipes?.[season]
  const source = recipe?.draft || recipe
  const loadSignature = JSON.stringify([document.data?.spec?.write_revision, document.data?.recipes?.ROY?.content_hash, document.data?.recipes?.MONSOON?.content_hash, document.data?.recipes?.ROY?.confirmed, document.data?.recipes?.MONSOON?.confirmed])
  useEffect(() => {
    if (document.data) onLoadRows?.({ ROY: document.data.recipes.ROY?.sheet_rows, MONSOON: document.data.recipes.MONSOON?.sheet_rows, monsoonConfirmed: document.data.recipes.MONSOON?.confirmed })
    // A background refetch must not reset a partially edited paper selection.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadSignature])
  const action = useMutation({ mutationFn: async (run: () => Promise<any>) => run(), onError: e => setError(errorText(e)), onSuccess: async () => { setError(""); setEditing(false); await Promise.all([cache.invalidateQueries({ queryKey: ["season-spec-document", specId] }), cache.invalidateQueries({ queryKey: ["spec-sheet-document", specId] }), cache.invalidateQueries({ queryKey: ["season-recipe-history", specId] }), cache.invalidateQueries({queryKey:["season-spec-qc",specId]}), cache.invalidateQueries({queryKey:["spec-summary"]}), cache.invalidateQueries({queryKey:["purchase-v2","sales-bom-demand"]})]) } })
  const revise = () => { setLayers(structuredClone(source.layers)); setNote(recipe.draft ? source.change_note : ""); setEditing(true) }
  const paperMap = new Map((papers.data || []).map((p: any) => [p.id, p]))
  const sheetRows = () => layers.map((layer, i) => { const p: any = paperMap.get(layer.paper_id); return { id: `season-ply-${i + 1}`, paper_id: layer.paper_id, positionsText: String(layer.ply_no), plyCount: 1, bfPerPly: layer.bf_snapshot, bulkFactor: layer.bulk_snapshot, thicknessPerPly: Number(layer.gsm_snapshot) * Number(layer.bulk_snapshot || 1) / 1000, gsm: layer.gsm_snapshot, code: p?.code || p?.paper_code || "" } })
  if (document.isLoading) return <p role="status" className="mt-3 text-sm">Loading seasonal recipe status…</p>
  if (document.isError) return <Button className="mt-3" variant="outline" onClick={() => document.refetch()}>Retry recipe status</Button>
  return <section className="my-4 space-y-3 rounded-xl border border-border bg-card p-4" data-testid="season-recipe-manager">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2">{(["ROY", "MONSOON"] as Season[]).map(s => <Button key={s} variant={s === season ? "default" : "outline"} onClick={() => { if (!editing || window.confirm("Discard this unsaved recipe revision?")) { setSeason(s); setEditing(false) } }}>{seasonLabel(s)} r{document.data?.recipes[s]?.season_revision || "—"}</Button>)}</div><Button variant="ghost" onClick={() => setShowHistory(!showHistory)}>Recipe history / diff</Button></div>
    {recipe && <div className="flex flex-wrap items-center gap-3 text-sm"><span className="font-semibold">{seasonLabel(season)} r{source.season_revision} · {source.status}</span><span className={recipe.confirmed ? "text-emerald-700" : "text-amber-700"}>{recipe.confirmed ? "Selection confirmed" : "Confirmation required"}</span>{recipe.draft && <span className="text-amber-700">A separate draft revision is open</span>}</div>}
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    {recipe && canEdit && <div className="flex flex-wrap gap-2">{!recipe.confirmed && <Button variant="outline" disabled={action.isPending} onClick={() => action.mutate(() => seasonApi.confirm(specId, season, command({ expected_version: document.data.spec.write_revision, note: "Recipe reviewed and confirmed" })))}>Confirm current {seasonLabel(season)} recipe</Button>}{document.data.spec.status === "approved" && <Button variant="outline" onClick={revise}>Revise {seasonLabel(season)} only</Button>}{recipe.draft && <Button disabled={!recipe.confirmed || action.isPending} onClick={() => action.mutate(() => seasonApi.approveRevision(specId, season, command({ expected_version: recipe.draft.row_version, note: "Reviewed seasonal recipe revision" })))}>Approve this revision</Button>}</div>}
    {editing && <div className="space-y-3 border-t border-border pt-4"><p className="text-sm text-muted-foreground">This creates a new {seasonLabel(season)} revision. The other season and released cards retain their recorded recipe.</p>{layers.map((layer, i) => <div key={i} className="flex flex-wrap items-center gap-2"><span className="w-12 text-sm">Ply {i + 1}</span><select aria-label={`Ply ${i + 1} paper`} className="h-10 min-w-48 flex-1 rounded-lg border border-border bg-background px-3 text-sm" value={layer.paper_id} onChange={e => { const p: any = paperMap.get(e.target.value); setLayers(current => current.map((v, index) => index === i ? { ...v, paper_id: e.target.value, gsm_snapshot: p?.gsm, bf_snapshot: p?.bf || p?.strength_value, bulk_snapshot: p?.bulk_factor || 1 } : v)) }}><option value="">Select paper</option>{(papers.data || []).map((p: any) => <option key={p.id} value={p.id}>{p.paper_code || p.code || p.name} · {p.gsm} GSM</option>)}</select><span className="text-xs text-muted-foreground">{layer.gsm_snapshot} GSM · BF {layer.bf_snapshot}</span><Button variant="ghost" onClick={() => setLayers(current => current.filter((_, index) => i !== index).map((v, index) => ({ ...v, ply_no: index + 1 })))}>Remove</Button></div>)}<Button variant="outline" onClick={() => setLayers(current => [...current, { ply_no: current.length + 1, paper_id: "", gsm_snapshot: 0, bf_snapshot: 0, bulk_snapshot: 1 }])}>Add ply</Button><Input aria-label="Recipe revision reason" placeholder="Reason for this seasonal change" value={note} onChange={e => setNote(e.target.value)} /><div className="flex gap-2"><Button disabled={!note.trim() || action.isPending || layers.some(l => !l.paper_id)} onClick={() => action.mutate(() => seasonApi.revision(specId, season, command({ expected_version: source.row_version, note, layers, sheet_rows: sheetRows(), confirm: false })))}>Save seasonal revision</Button><Button variant="ghost" onClick={() => setEditing(false)}>Cancel</Button></div></div>}
    <details><summary className="cursor-pointer text-sm font-semibold">Effective {seasonLabel(season)} QC tolerances</summary>{qc.isLoading ? <p>Resolving tolerances…</p> : qc.isError ? <p className="mt-2 text-sm text-amber-700">Publish the seasonal QC rules to resolve this spec.</p> : <div className="mt-3 space-y-3">{["WINDER", "OVEN", "PROCESS"].map(stage => <div key={stage}><p className="text-xs font-semibold uppercase text-muted-foreground">{stage === "WINDER" ? "Winding" : stage}</p><div className="mt-1 flex flex-wrap gap-2">{qc.data?.stages?.[stage]?.parameters.map((r: any) => <span key={r.code} className="rounded-lg bg-muted px-2 py-1 text-xs">{r.label}: {qcRangeLabel(r)}{r.overlay_id ? " · Override" : ""}</span>)}</div></div>)}{(qc.data?.unresolved?.length || qc.data?.conflicts?.length) ? <p className="text-sm text-destructive">Resolve {qc.data.unresolved.length} missing references and {qc.data.conflicts.length} conflicts before release.</p> : <p className="text-xs text-muted-foreground">Global QC version {qc.data?.provenance?.rule_set_version} · minimum two samples per required parameter</p>}</div>}</details>
    {showHistory && <div className="border-t border-border pt-3">{history.isLoading ? <p>Loading history…</p> : history.data?.map((v: any, i: number, all: any[]) => <div key={v.id} className="mb-3 rounded-lg bg-muted p-3 text-sm"><strong>r{v.season_revision} · {v.status}</strong><p>{v.change_note} · {v.created_by}</p>{all[i + 1] && <div className="mt-2 space-y-1 text-xs">{Array.from(new Set<number>([...v.layers,...all[i+1].layers].map((l:any)=>Number(l.ply_no)))).sort((a,b)=>a-b).map(ply=>{const before=all[i+1].layers.find((l:any)=>l.ply_no===ply);const after=v.layers.find((l:any)=>l.ply_no===ply);const format=(l:any)=>l?`${String(l.paper_id).slice(0,8)} · ${l.gsm_snapshot} GSM · BF ${l.bf_snapshot} · bulk ${l.bulk_snapshot}`:"Absent";return JSON.stringify(before)===JSON.stringify(after)?null:<p key={ply}>Ply {ply}: {format(before)} → {format(after)}</p>})}</div>}</div>)}</div>}
  </section>
}
