#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
resolve_runtime_dir() {
  local erp_dir="$1"
  if [[ -n "${ERP_RUNTIME_DIR:-}" ]]; then
    echo "${ERP_RUNTIME_DIR}"
    return
  fi
  if [[ -d "${erp_dir}/runtime" || ! -e "${erp_dir}/.runtime" ]]; then
    echo "${erp_dir}/runtime"
    return
  fi
  echo "${erp_dir}/.runtime"
}

RUNTIME_DIR="$(resolve_runtime_dir "${BASE_DIR}/hariom-erp")"
PID_DIR="${RUNTIME_DIR}/pids"
MANIFEST_PATH="${RUNTIME_DIR}/runtime_manifest.json"
resolve_runtime_venv_dir() {
  local erp_dir="$1"
  if [[ -n "${ERP_VENV_DIR:-}" ]]; then
    echo "${ERP_VENV_DIR}"
    return
  fi
  if [[ -d "${erp_dir}/venv-runtime" || ! -e "${erp_dir}/.venv-runtime" ]]; then
    echo "${erp_dir}/venv-runtime"
    return
  fi
  echo "${erp_dir}/.venv-runtime"
}

RUNTIME_PYTHON="$(resolve_runtime_venv_dir "${BASE_DIR}/hariom-erp")/bin/python3.11"
INTEGRITY_SCRIPT="${BASE_DIR}/scripts/runtime_integrity.py"

TARGET_PORTS=(
  3101
  13000
  13001
  14000
  14001
  18001
  18002
  18003
  18004
  18005
  18006
  18007
  18008
  18009
  18010
  18011
  18012
  18013
  18014
)

stop_port() {
  local port="$1"
  local pids=""
  if command -v lsof >/dev/null 2>&1; then
    pids="$(lsof -tiTCP:"${port}" -sTCP:LISTEN 2>/dev/null || true)"
  fi
  if [[ -z "$pids" ]]; then
    return 0
  fi
  for pid in $pids; do
    kill "$pid" >/dev/null 2>&1 || true
  done
  sleep 1
  for pid in $pids; do
    if kill -0 "$pid" >/dev/null 2>&1; then
      kill -9 "$pid" >/dev/null 2>&1 || true
    fi
  done
}

cleanup_stale_runtime_artifacts() {
  rm -f "${RUNTIME_DIR}"/runtime_manifest\ *.json
  rm -f "${RUNTIME_DIR}"/ports\ *.env
  rm -f "${RUNTIME_DIR}"/orchestrator\ *.env
}

scope_dataless_count() {
  /usr/bin/env python3 "${INTEGRITY_SCRIPT}" count --scope "$1"
}

echo "[verified-runtime] stopping managed runtime..."
ERP_RUNTIME_DIR="${RUNTIME_DIR}" "${BASE_DIR}/stop_all.sh" >/dev/null 2>&1 || true

echo "[verified-runtime] reclaiming stale ports..."
for port in "${TARGET_PORTS[@]}"; do
  stop_port "$port"
done

cleanup_stale_runtime_artifacts
rm -f "$MANIFEST_PATH"
if [[ -d "$PID_DIR" ]]; then
  find "$PID_DIR" -maxdepth 1 -type f -name '*.pid' -delete >/dev/null 2>&1 || true
fi

export AUTH_PORT="${AUTH_PORT:-18001}"
export MASTER_PORT="${MASTER_PORT:-18002}"
export SPEC_PORT="${SPEC_PORT:-18003}"
export PRODUCTION_PORT="${PRODUCTION_PORT:-18004}"
export INVENTORY_PORT="${INVENTORY_PORT:-18005}"
export ANALYTICS_PORT="${ANALYTICS_PORT:-18007}"
export SALES_PORT="${SALES_PORT:-18008}"
export BFF_PORT="${BFF_PORT:-14000}"
export WEB_UI_PORT="${WEB_UI_PORT:-13000}"
# Verified demo runs should reuse the explicit production build generated by
# run_verification.sh so the browser gate avoids Next dev-only runtime bugs.
export WEB_UI_MODE="${WEB_UI_MODE:-prod}"
export START_WEB_UI="${START_WEB_UI:-1}"
export WEB_UI_TURBO="${WEB_UI_TURBO:-0}"
export WEB_UI_SOURCE_BUILD="${WEB_UI_SOURCE_BUILD:-0}"
export STARTUP_PREFLIGHT="${STARTUP_PREFLIGHT:-1}"

echo "[verified-runtime] hydrating local placeholder files..."
/usr/bin/env python3 "${BASE_DIR}/scripts/hydrate_local_placeholders.py" \
  --scope backend-source \
  --scope web-source

backend_remaining="$(scope_dataless_count backend-source)"
if [[ "$backend_remaining" != "0" ]]; then
  echo "[verified-runtime] recovering remaining backend Python placeholders from local bytecode..."
  /usr/bin/env python3 "${BASE_DIR}/scripts/recover_dataless_python_from_pyc.py"
fi

backend_remaining="$(scope_dataless_count backend-source)"
web_remaining="$(scope_dataless_count web-source)"
if [[ "$backend_remaining" != "0" || "$web_remaining" != "0" ]]; then
  echo "[verified-runtime] unresolved source files remain after hydration"
  /usr/bin/env python3 "${INTEGRITY_SCRIPT}" check --scope backend-source --scope web-source
  exit 1
fi

echo "[verified-runtime] starting fresh runtime..."
"${BASE_DIR}/start_all.sh"

if [[ ! -x "${RUNTIME_PYTHON}" ]]; then
  echo "Runtime python missing after startup: ${RUNTIME_PYTHON}"
  exit 1
fi

echo "[verified-runtime] verifying live consistency..."
"${RUNTIME_PYTHON}" "${BASE_DIR}/scripts/verify_runtime_consistency.py" --write-manifest

echo "[verified-runtime] ready"
echo "manifest: ${MANIFEST_PATH}"
