"use client"

import Link from "next/link"
import { ResidualWipPanel } from "./ResidualWipPanel"
import { InstrumentFields } from "./InstrumentFields"
import { FinalQcForm } from "./FinalQcForm"
import { WholeCardEntryForm } from "./WholeCardEntryForm"
import { useEffect, useRef, useState } from "react"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useAuth } from "@/context/AuthContext"
import { entryApiForPlant, command, errorText, seasonLabel } from "@/lib/season-api"

const label = (stage: string) => stage === "WINDER" ? "Winding" : stage === "QC" ? "QC" : stage.charAt(0) + stage.slice(1).toLowerCase()
const verdictLabels:Record<string,string>={NOT_MEASURED:"Awaiting readings",OBSERVATION_ONLY:"Recorded",PASS:"Pass",FAIL:"Fail",INCOMPLETE:"Incomplete",INVALID:"Invalid"}
const verdictLabel=(value:string)=>verdictLabels[value] || value || "Awaiting readings"
const count = (value: string) => value === "" ? 0 : Number(value)
const selectClass = "h-10 w-full rounded-lg border border-border bg-background px-3 text-sm"
const range = (r: any) => !r.applicable ? "Not applicable" : r.dynamic ? `${r.lower.map((t:any) => `Pre-weight × ${t.factor} ${t.offset ? `+ ${t.offset}` : ""}`).join(" / ")} to ${r.upper.map((t:any) => `Pre-weight × ${t.factor} ${t.offset ? `+ ${t.offset}` : ""}`).join(" / ")}` : r.mode === "RECORD_ONLY" ? "Record only" : `${r.min ?? "—"} to ${r.max ?? "—"} ${r.unit}`

export function ContinuousJobCard({ card, print = false }: { card: any; print?: boolean }) {
  const { user } = useAuth()
  const entryApi=entryApiForPlant(card.plant_id)
  const cache = useQueryClient()
  const [stage, setStage] = useState("WINDER")
  const [page, setPage] = useState(0)
  const [showForm, setShowForm] = useState(false)
  const [wholeCard,setWholeCard] = useState(false)
  const [qcOnly, setQcOnly] = useState(false)
  const [totalMode, setTotalMode] = useState(false)
  const [produced, setProduced] = useState("")
  const [accepted, setAccepted] = useState("")
  const [input, setInput] = useState("")
  const [loss, setLoss] = useState("")
  const [carryIn, setCarryIn] = useState("")
  const [carryOut, setCarryOut] = useState("")
  const [shift, setShift] = useState("")
  const [operator, setOperator] = useState("")
  const [segment,setSegment] = useState("")
  const [businessDate, setBusinessDate] = useState(new Date().toLocaleDateString("en-CA"))
  const [reason, setReason] = useState("")
  const [supervisor, setSupervisor] = useState("")
  const [closing, setClosing] = useState(false)
  const [fgItem,setFgItem]=useState("")
  const [location,setLocation]=useState("")
  const [startTime,setStartTime]=useState("")
  const [endTime,setEndTime]=useState("")
  const [reelLinks,setReelLinks] = useState<string[]>([])
  const [residual, setResidual] = useState("HOLD")
  const [instrument,setInstrument] = useState<any>({})
  const [samples, setSamples] = useState<any[]>([])
  const [editing, setEditing] = useState<any>(null)
  const [history, setHistory] = useState<any>(null)
  const [error, setError] = useState("")
  const pending = useRef<{fingerprint:string;body:any}|null>(null)
  const roles = new Set([user?.role, ...(user?.roles || [])])
  const canSubmit = ["Owner", "Admin", "PlantManager"].some(r => roles.has(r))
  const canReopen = ["Owner", "Admin"].some(r => roles.has(r))
  const canQc = ["Owner", "Admin", "QC"].some(r => roles.has(r))
  const canDraft = canSubmit || roles.has("Operator")
  const flow = useQuery({ queryKey: ["continuous-flow", card.id], queryFn: async () => (await entryApi.flow(card.id)).data, refetchInterval: print ? false : 15000 })
  const listing = useQuery({ queryKey: ["continuous-entries", card.id, stage, page, print], queryFn: async () => {
    if (!print) return (await entryApi.list(card.id, stage, page * 50)).data
    const all:any[] = []; let offset = 0; let total = 1
    while(offset < total) { const d=(await entryApi.list(card.id, undefined, offset, 100)).data;all.push(...d.entries);total=d.total;offset+=100 }
    return {entries:all,total:all.length}
  } })
  const employees=useQuery({queryKey:["continuous-employees",card.plant_id],queryFn:async()=>(await entryApi.employees()).data,enabled:!print})
  const effects=useQuery({queryKey:["continuous-effects",card.id],queryFn:async()=>(await entryApi.effects(card.id)).data,enabled:!print,refetchInterval:print?false:15000})
  const items=useQuery({queryKey:["continuous-items",card.plant_id],queryFn:async()=>(await entryApi.items()).data,enabled:!print})
  const locations=useQuery({queryKey:["continuous-locations",card.plant_id],queryFn:async()=>(await entryApi.locations()).data,enabled:!print})
  const winderMachine=card.stages?.find((s:any)=>s.stage_type==="WINDER")?.machine_id
  const reelIssues=useQuery({queryKey:["continuous-reel-issues",card.id,winderMachine],queryFn:async()=>(await entryApi.reelIssues(winderMachine)).data,enabled:Boolean(winderMachine && closing && stage==="WINDER")})
  const state = flow.data?.stages?.find((s: any) => s.stage === stage)
  const parameters = card.spec_snapshot?.qc_profile?.stages?.[stage]?.parameters?.filter((r:any) => r.applicable) || []
  const profile = card.spec_snapshot?.qc_profile
  const mutation = useMutation({ mutationFn: async (action: () => Promise<any>) => action(), onError: e => setError(errorText(e)), onSuccess: async () => { pending.current = null;setError("");setShowForm(false);setClosing(false);setEditing(null);await Promise.all([cache.invalidateQueries({queryKey:["continuous-flow",card.id]}),cache.invalidateQueries({queryKey:["continuous-entries",card.id]}),cache.invalidateQueries({queryKey:["planning-job-card",card.id]})]) } })
  const stableCommand = (body:any) => {const fingerprint=JSON.stringify(body);if(!pending.current || pending.current.fingerprint!==fingerprint) pending.current={fingerprint,body:command(body)};return pending.current.body}
  const newForm = (entry?:any, observationOnly=false) => {
    setInstrument(entry?.details?.instrument || {});setSegment(entry?.segment_id || state?.segments?.filter((s:any)=>!["COMPLETED","CANCELLED"].includes(s.status))[0]?.id || "");setStartTime(entry?.details?.start_time || "");setEndTime(entry?.details?.end_time || "");setEditing(entry || null);setQcOnly(observationOnly);setTotalMode(false);setProduced(entry?.produced?.toString() || "");setAccepted(entry?.accepted?.toString() || "");setInput(entry?.input_quantity?.toString() || "");setLoss(entry?.cutting_loss_pcs?.toString() || "");setCarryIn(entry?.carry_in_pcs?.toString() || "");setCarryOut(entry?.carry_out_pcs?.toString() || "");setShift(entry?.shift_code || "");setOperator(entry?.operator_id || "");setReason("");setBusinessDate(entry?.business_date || new Date().toLocaleDateString("en-CA"));setSamples(entry?.samples || [1,2].map(i => ({sample_id:`${crypto.randomUUID()}-${i}`,readings:{}})));setShowForm(true);setClosing(false);setError("");pending.current=null
  }
  useEffect(() => { if(flow.data?.stages?.length && !flow.data.stages.some((s:any)=>s.stage===stage)) setStage(flow.data.stages[0].stage) }, [flow.data,stage])
  const save = (submit:boolean) => {
    const body:any={stage,kind:qcOnly?"QC_ONLY":stage==="PROCESS" && count(produced)===0 && count(carryIn)>0?"DISPOSITION":"PRODUCTION",quantity_mode:totalMode?"TOTAL":"DELTA",expected_version:editing?.row_version ?? state?.row_version,business_date:qcOnly?null:businessDate,shift_code:qcOnly?null:shift || null,operator_id:qcOnly?null:operator || null,segment_id:qcOnly?null:segment || null,produced:qcOnly?0:count(produced),accepted:qcOnly?0:count(accepted),input_quantity:qcOnly?0:count(input),cutting_loss_pcs:qcOnly?0:count(loss),carry_in_pcs:qcOnly?0:count(carryIn),carry_out_pcs:qcOnly?0:count(carryOut),samples:samples.filter(s=>Object.values(s.readings).some(v=>v!=="" && v!=null)).map(s=>({...s,readings:Object.fromEntries(Object.entries(s.readings).filter(([,v])=>v!=="" && v!=null))})),details:{reject_reason:reason,overproduction_reason:reason,carryover_reason:reason,start_time:startTime || null,end_time:endTime || null,instrument},reason,submit}
    if(editing && qcOnly) mutation.mutate(()=>entryApi.observations(card.id,editing.id,stableCommand({samples:body.samples,instrument,expected_version:editing.row_version,reason})))
    else if(editing) mutation.mutate(()=>entryApi.edit(card.id,editing.id,stableCommand({...body,submit:false})))
    else mutation.mutate(()=>entryApi.create(card.id,stableCommand(body)))
  }
  if(flow.isLoading || listing.isLoading) return <p role="status" className="p-6">Loading production entries…</p>
  if(flow.isError || listing.isError) return <div className="rounded-xl border border-destructive p-6"><p>Production entries could not be loaded.</p><Button onClick={()=>{flow.refetch();listing.refetch()}}>Retry</Button></div>
  if(print) return <section className="break-before-page space-y-4 bg-white p-6 text-black"><h2 className="text-xl font-bold">Production and QC annex · {card.job_card_no}</h2><p className="break-all text-sm">{seasonLabel(flow.data.season)} · recipe r{flow.data.recipe_revision} · QC v{profile?.provenance?.rule_set_version} · bundle {card.spec_snapshot?.release_bundle_hash}</p>{flow.data.stages.map((s:any)=><p key={s.stage} className="text-sm">{label(s.stage)} · {s.status} · accepted {s.accepted_total}/{s.target} {s.unit}{s.supervisor_name?` · supervisor name: ${s.supervisor_name}`:""}{s.closed_at?` · closed ${s.closed_at}`:""}</p>)}{flow.data.stages.filter((s:any)=>profile?.stages?.[s.stage]).map((s:any)=>[s.stage,profile.stages[s.stage]]).map(([name,value]:any)=><div key={name}><h3 className="font-bold">{label(name)}</h3>{value.parameters.map((r:any)=><p key={r.code}>{r.label}: {range(r)} · {r.min_readings} readings {r.overlay_id?`· overlay ${r.overlay_id} v${r.overlay_version}`:""}</p>)}</div>)}<ResidualWipPanel rows={flow.data.residual_wip} print/><h3 className="font-bold">Final customer acceptance</h3>{flow.data.final_samples?.map((s:any)=><div key={s.sample_id} className="break-inside-avoid border-t pt-2 text-sm"><p>Sample {s.sample_id} · {s.status} · QC {s.qc_name} · {s.recorded_at}{s.workflow_status?` · ${s.workflow_status}`:""}</p><p>{Object.entries(s.readings || {}).filter(([k])=>["id","od","length","weight","cs"].includes(k)).map(([k,v])=>`${k}: ${v}`).join(" · ")}</p></div>)}{[...listing.data.entries].sort((a:any,b:any)=>flow.data.stages.findIndex((s:any)=>s.stage===a.stage)-flow.data.stages.findIndex((s:any)=>s.stage===b.stage) || a.entry_no-b.entry_no).map((e:any)=><div className="break-inside-avoid border-t pt-3" key={e.id}><p className="font-semibold">{label(e.stage)} #{e.entry_no} · {e.status} · {e.business_date} {e.shift_code} · {e.operator_name} ({e.operator_code}) · produced {e.produced}, accepted {e.accepted}, rejected {e.rejected}</p>{e.evaluation?.results?.map((r:any)=><p className="text-sm" key={`${r.sample_id}-${r.parameter}`}>{r.sample_id}: {r.parameter} {r.value} · {r.verdict}</p>)}</div>)}</section>
  return <div className="mx-auto max-w-7xl space-y-5" data-testid="continuous-job-card">
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-5"><div><p className="text-xs uppercase text-muted-foreground">Frozen production contract</p><h1 className="text-xl font-semibold">{card.job_card_no || "Job card"} · {seasonLabel(flow.data.season)}</h1><p className="text-sm text-muted-foreground">Recipe r{flow.data.recipe_revision} · QC v{profile?.provenance?.rule_set_version} · {flow.data.pending_effects} postings pending</p></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline"><Link href={`/production/job-cards/${card.id}/print`}>Print card and QC annex</Link></Button><Button asChild variant="outline"><Link href={`/quality/results?job_card_id=${card.id}`}>QC results / holds</Link></Button><Button asChild variant="outline"><Link href="/inventory/production-issue">Material issues</Link></Button></div></div>
    <nav aria-label="Production stages" className="flex flex-wrap gap-2">{flow.data.stages.map((s:any)=><Button key={s.stage} variant={s.stage===stage?"default":"outline"} onClick={()=>{if((!showForm && !closing)||window.confirm("Discard unsaved entry?")){setStage(s.stage);setPage(0);setShowForm(false);setClosing(false)}}}>{label(s.stage)} · {s.accepted_total}/{s.target} {s.unit}{s.status==="COMPLETED"?" ✓":""}</Button>)}</nav>
    {error && <p role="alert" className="rounded-lg border border-destructive bg-destructive/5 p-3 text-sm text-destructive">{error}</p>}
    {state && <section className="space-y-4 rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-lg font-semibold">{label(stage)} · {state.status}</h2><p className="text-sm text-muted-foreground">Produced {state.produced_total} · Accepted {state.accepted_total} · Rejected {state.rejected_total} {state.unit}{state.available_from_upstream!=null?` · Available input ${state.available_from_upstream} ${state.input_unit}`:""}{stage==="PROCESS"?` · Held carryover ${state.carryover_pcs} pcs`:""}</p></div>{state.status!=="COMPLETED" && stage!=="SLITTING" && stage!=="DISPATCH" && <div className="flex flex-wrap gap-2">{canDraft && <Button onClick={()=>newForm()}>Add production entry</Button>}{canQc && parameters.length>0 && <Button variant="outline" onClick={()=>newForm(undefined,true)}>Add QC observations</Button>}{canSubmit && <Button variant="outline" onClick={()=>{setClosing(true);setShowForm(false);setReason("")}}>Close stage</Button>}</div>}</div>
      {stage==="SLITTING" && <Button asChild variant="outline"><Link href={`/production/job-cards/${card.id}/slitting`}>Open Slitting material preparation</Link></Button>}
      {state.status==="COMPLETED" && <div className="flex flex-wrap items-center gap-3"><p className="text-sm">Closed by supervisor {state.supervisor_name} · {state.closed_at}{state.residual_quantity?` · ${state.residual_quantity} unused input ${state.residual_disposition}`:""}</p>{canReopen && !["SLITTING","DISPATCH"].includes(stage) && <Button size="sm" variant="outline" disabled={mutation.isPending} onClick={()=>{const reason=window.prompt("Reason to reopen this stage. Posted stock or tool usage requires a governed reversal or additional card.");if(reason?.trim())mutation.mutate(()=>entryApi.reopen(card.id,stage,stableCommand({expected_version:state.row_version,reason})))}}>Reopen stage</Button>}</div>}
      {state.blockers.length>0 && <div className="rounded-lg bg-muted p-3 text-sm">{state.blockers.map((b:string)=><p key={b}>{b}</p>)}{state.qc.missing.map((r:any)=><span className="mr-3 text-xs" key={r.parameter}>{r.label}: {r.have}/{r.need} samples</span>)}</div>}
      <details><summary className="cursor-pointer text-sm font-semibold">Frozen tolerances and provenance</summary><div className="mt-3 grid gap-2 sm:grid-cols-2">{parameters.map((r:any)=><div key={r.code} className="rounded-lg border border-border p-3 text-sm"><strong>{r.label}</strong><p>{range(r)} · minimum {r.min_readings} samples</p><p className="text-xs text-muted-foreground">{r.overlay_id?`Customer/spec overlay v${r.overlay_version}`:`Global ${seasonLabel(flow.data.season)} v${profile?.provenance?.rule_set_version}`}</p></div>)}</div></details>
    </section>}
    {canSubmit && flow.data.stages.some((s:any)=>!["COMPLETED","CANCELLED"].includes(s.status) && !["DISPATCH","SLITTING"].includes(s.stage)) && <Button variant="outline" onClick={()=>{setWholeCard(true);setShowForm(false);setClosing(false)}}>Enter whole card</Button>}
    {wholeCard && <WholeCardEntryForm card={card} flow={flow.data} onDone={()=>setWholeCard(false)}/>}
    {stage==="QC" && canQc && <FinalQcForm card={card}/>}
    {stage==="DISPATCH" && <Button asChild><Link href="/logistics/dispatch">Open Logistics Dispatch</Link></Button>}
    {effects.data?.length>0 && <details className="rounded-xl border border-border bg-card p-4"><summary className="cursor-pointer text-sm font-semibold">Production postings · {flow.data.pending_effects} pending</summary>{effects.data.map((e:any)=><div key={e.id} className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-border pt-3 text-sm"><div><p>{label(e.stage || "")} · {e.kind.replaceAll("_"," ")} · {e.status}</p>{e.last_error && <p className="text-destructive">{e.last_error}</p>}<p className="text-xs text-muted-foreground">Attempts {e.attempts}{e.status==="FAILED"?` · Next automatic retry ${new Date(e.next_attempt_at).toLocaleString()}`:""}</p></div>{canSubmit && e.status==="FAILED" && <Button variant="outline" disabled={mutation.isPending} onClick={()=>mutation.mutate(async()=>{const r=await entryApi.retryEffect(card.id,e.id,stableCommand({expected_version:e.attempts,reason:"Supervisor requested retry after reviewing posting failure"}));await effects.refetch();return r})}>Retry posting</Button>}</div>)}</details>}
    <ResidualWipPanel rows={flow.data.residual_wip} canResolve={canSubmit} busy={mutation.isPending} onResolve={(row,disposition,reason)=>mutation.mutate(()=>entryApi.resolveResidual(card.id,row.id,stableCommand({expected_version:row.row_version,disposition,reason})))}/>
    {showForm && <section className="space-y-4 rounded-xl border border-border bg-card p-5"><h2 className="text-lg font-semibold">{editing?`Revise entry #${editing.entry_no}`:qcOnly?"QC observations":"Production entry"} · {label(stage)}</h2>{!qcOnly && <><label className="block text-sm">Scheduled segment<select className={selectClass} value={segment} onChange={e=>setSegment(e.target.value)}><option value="">Choose scheduled segment</option>{(state.segments || []).filter((s:any)=>!["COMPLETED","CANCELLED"].includes(s.status)).map((s:any)=><option key={s.id} value={s.id}>{s.plan_date || "Unscheduled"} · {s.shift_code?.replace("SHIFT_","Shift ") || "No shift"} · machine {s.machine_id?.slice(0,8) || "unassigned"}</option>)}</select></label><div className="flex items-center gap-3 text-sm"><label><input type="checkbox" checked={totalMode} disabled={!!editing || !canSubmit} onChange={e=>setTotalMode(e.target.checked)} /> Enter cumulative totals</label>{totalMode && <span>Will post delta: produced {count(produced)-state.produced_total}, accepted {count(accepted)-state.accepted_total}, input {count(input)-state.input_total}</span>}</div><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Business date *<Input type="date" value={businessDate} onChange={e=>setBusinessDate(e.target.value)} /></label><label className="text-sm">Shift *<select className={selectClass} value={shift} onChange={e=>setShift(e.target.value)}><option value="">Choose shift</option><option value="SHIFT_A">Shift A</option><option value="SHIFT_B">Shift B</option></select></label><label className="text-sm">Operator name / ID *<select className={selectClass} value={operator} onChange={e=>setOperator(e.target.value)}><option value="">Choose operator</option>{(employees.data || []).filter((e:any)=>e.active && String(e.role).toLowerCase()==="operator").map((e:any)=><option key={e.id} value={e.id}>{e.name} · {e.employee_code}</option>)}</select></label>{[["Quantity produced *",produced,setProduced],["Accepted quantity *",accepted,setAccepted],[`Input ${state.input_unit || "quantity"}`,input,setInput],...(stage==="PROCESS"?[["Cutting loss pcs",loss,setLoss],["Held carry-in pcs",carryIn,setCarryIn],["Held carry-out pcs",carryOut,setCarryOut]]:[])].map(([title,value,setter]:any)=><label className="text-sm" key={title}>{title}<Input inputMode="numeric" type="number" min="0" step="1" value={value} onChange={e=>setter(e.target.value)} /></label>)}</div><p className="text-sm">Rejected quantity: {count(produced)-count(accepted)} {state.unit}. Produced may equal accepted. Start/end times are optional.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Start time (optional)<Input type="datetime-local" value={startTime} onChange={e=>setStartTime(e.target.value)} /></label><label className="text-sm">End time (optional)<Input type="datetime-local" value={endTime} onChange={e=>setEndTime(e.target.value)} /></label></div></>}
      {parameters.length>0 && <div className="space-y-3"><p className="text-sm text-muted-foreground">QC can be recorded later. Stage close requires at least two distinct samples for every required parameter. Keep oven pre/post measurements on the same sample.</p>{samples.map((sample,i)=><div key={sample.sample_id} className="rounded-lg border border-border p-3"><p className="mb-2 text-sm font-semibold">Sample {i+1} · {sample.sample_id.slice(0,8)}</p><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5">{parameters.map((r:any)=><label className="text-xs" key={r.code}>{r.label} ({r.unit})<Input type="number" step="any" value={sample.readings[r.code] ?? ""} onChange={e=>setSamples(current=>current.map((v,index)=>index===i?{...v,readings:{...v.readings,[r.code]:e.target.value}}:v))} /><span className="text-muted-foreground">{range(r)}</span></label>)}</div></div>)}<Button variant="outline" onClick={()=>setSamples(current=>[...current,{sample_id:crypto.randomUUID(),readings:{}}])}>Add sample</Button></div>}
      {parameters.some((p:any)=>p.requires_instrument) && <InstrumentFields value={instrument} onChange={setInstrument}/>}
      <Input placeholder="Reason for rejects, loss, carryover, excess output or correction" aria-label="Entry reason" value={reason} onChange={e=>setReason(e.target.value)} /><div className="flex gap-2">{!qcOnly && !totalMode && <Button variant="outline" disabled={mutation.isPending} onClick={()=>save(false)}>{editing?"Save draft changes":"Save draft"}</Button>}{(canSubmit || qcOnly && canQc) && !editing?.status?.includes("DRAFT") && <Button disabled={mutation.isPending || !qcOnly && (!produced || !accepted || !operator || !shift)} onClick={()=>save(true)}>{editing?"Save QC correction":"Submit entry"}</Button>}<Button variant="ghost" onClick={()=>setShowForm(false)}>Cancel</Button></div>
    </section>}
    {closing && <section className="space-y-3 rounded-xl border border-border bg-card p-5"><h2 className="font-semibold">Close {label(stage)}</h2><label className="text-sm">Supervisor name *<select className={selectClass} value={supervisor} onChange={e=>setSupervisor(e.target.value)}><option value="">Choose supervisor</option>{(employees.data || []).filter((e:any)=>e.active && String(e.role).toLowerCase()==="supervisor").map((e:any)=><option key={e.id} value={e.id}>{e.name} · {e.employee_code}</option>)}</select></label>{stage==="WINDER" && <details><summary className="cursor-pointer text-sm font-semibold">Link consumed material issues</summary>{reelIssues.isError?<p className="text-sm text-destructive">Could not load reel issues. Retry after checking Inventory.</p>:(reelIssues.data || []).filter((i:any)=>!i.sales_order_id || i.sales_order_id===card.sales_order_id).map((i:any)=><label key={i.id} className="mt-2 block text-sm"><input type="checkbox" checked={reelLinks.includes(i.id)} onChange={e=>setReelLinks(current=>e.target.checked?[...current,i.id]:current.filter(id=>id!==i.id))}/> {i.reel_code || i.amigo_no || i.id.slice(0,8)} · {i.consumed_weight_kg} kg · {i.issue_date}</label>)}</details>}{stage==="PACKING" && <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Finished-good item *<select className={selectClass} value={fgItem} onChange={e=>setFgItem(e.target.value)}><option value="">Choose finished good</option>{(items.data || []).filter((i:any)=>i.type==="FINISHED_GOOD").map((i:any)=><option key={i.id} value={i.id}>{i.item_code || i.code} · {i.name}</option>)}</select></label><label className="text-sm">Stock location<select className={selectClass} value={location} onChange={e=>setLocation(e.target.value)}><option value="">Default location</option>{(locations.data || []).map((l:any)=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div>}{state.available_from_upstream>0 && <label className="text-sm">Unused input disposition<select className={selectClass} value={residual} onChange={e=>setResidual(e.target.value)}><option value="HOLD">Hold for follow-up</option><option value="RETURN">Return unused input</option><option value="SCRAP">Scrap with reason</option></select></label>}<Input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Short-close, material issue exception or residual WIP reason" aria-label="Close reason" /><Button disabled={mutation.isPending || !supervisor || !state.qc.ready || state.draft_count>0} onClick={()=>mutation.mutate(()=>entryApi.close(card.id,stage,stableCommand({expected_version:state.row_version,supervisor_id:supervisor,reel_issue_ids:stage==="WINDER"?reelLinks:[],fg_item_id:stage==="PACKING"?fgItem || null:null,location_id:location || null,short_close:state.accepted_total<state.target,residual_disposition:residual,reason})))}>Confirm stage close</Button><Button variant="ghost" onClick={()=>setClosing(false)}>Cancel</Button></section>}
    <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="flex justify-between p-4"><h2 className="font-semibold">Entry history · {listing.data.total}</h2><p className="text-xs text-muted-foreground">Drafts do not add to production totals</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y border-border bg-muted"><tr>{["Entry / date","Shift / operator","Produced","Accepted","Rejected","QC / status","Actions"].map(h=><th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{listing.data.entries.map((e:any)=><tr key={e.id} className="border-b border-border"><td className="px-4 py-3">#{e.entry_no}<p className="text-xs text-muted-foreground">{e.business_date || "QC only"}</p></td><td className="px-4 py-3">{e.shift_code?.replace("SHIFT_","Shift ")}<p>{e.operator_name} {e.operator_code?`· ${e.operator_code}`:""}</p></td><td className="px-4">{e.produced}</td><td className="px-4">{e.accepted}</td><td className="px-4">{e.rejected}</td><td className="px-4">{e.stage==="QC"?state.qc.ready?"Final QC ready":"Final QC pending":verdictLabel(e.evaluation?.verdict)}<p className="text-xs text-muted-foreground">{e.status} · revision {e.row_version}{e.details?.qc_name?` · QC ${e.details.qc_name}`:""}</p></td><td className="px-4"><div className="flex flex-wrap gap-1">{e.status==="DRAFT" && canDraft && <Button size="sm" variant="ghost" onClick={()=>newForm(e)}>Edit</Button>}{e.status==="DRAFT" && canSubmit && <Button size="sm" disabled={mutation.isPending} onClick={()=>mutation.mutate(()=>entryApi.submit(card.id,e.id,stableCommand({expected_version:e.row_version,reason:"Reviewed draft"})))}>Submit</Button>}{e.status==="SUBMITTED" && canQc && <Button size="sm" variant="ghost" onClick={()=>newForm(e,true)}>QC</Button>}{e.status!=="VOID" && canSubmit && state.status!=="COMPLETED" && <Button size="sm" variant="ghost" onClick={()=>{const reason=window.prompt("Reason to void this entry (consumed output cannot be voided)");if(reason)mutation.mutate(()=>entryApi.void(card.id,e.id,stableCommand({expected_version:e.row_version,reason})))}}>Void</Button>}<Button size="sm" variant="ghost" onClick={async()=>{try{setHistory((await entryApi.history(card.id,e.id)).data)}catch(e){setError(errorText(e))}}}>Audit</Button></div></td></tr>)}</tbody></table></div>{listing.data.total===0 && <p className="p-8 text-center text-sm text-muted-foreground">No entries for this stage. Add a draft, production output or QC observations.</p>}<div className="flex justify-between p-3"><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button variant="outline" disabled={(page+1)*50>=listing.data.total} onClick={()=>setPage(p=>p+1)}>Next</Button></div></section>
    {history && <section className="rounded-xl border border-border bg-card p-4"><Button variant="ghost" onClick={()=>setHistory(null)}>Close audit</Button>{history.map((r:any)=><details key={r.version}><summary className="cursor-pointer py-2">Revision {r.version} · {r.actor} · {r.reason}</summary><pre className="max-h-96 overflow-auto text-xs">{JSON.stringify(r.payload,null,2)}</pre></details>)}</section>}
  </div>
}
